# Generated by Django 1.9.11 on 2016-11-23 11:56
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('prison', '0011_prisonerlocation_active'),
    ]
    operations = [
        migrations.CreateModel(
            name='DigitalTakeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credits_by_post', models.IntegerField(verbose_name='Credits by post')),
                ('credits_by_mtp', models.IntegerField(verbose_name='Credits sent digitally')),
                ('prison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.Prison')),
            ],
            options={
                'verbose_name': 'digital take-up',
                'verbose_name_plural': 'digital take-up',
                'ordering': ('start_date',),
                'get_latest_by': 'start_date',
            },
        ),
        migrations.AlterUniqueTogether(
            name='digitaltakeup',
            unique_together={('start_date', 'end_date', 'prison')},
        ),
    ]
