# Generated by Django 2.2.22 on 2021-06-04 16:01
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('performance', '0004_retire_performance_platform'),
    ]
    operations = [
        migrations.CreateModel(
            name='UserSatisfaction',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rated_1', models.PositiveIntegerField(verbose_name='Very dissatisfied')),
                ('rated_2', models.PositiveIntegerField(verbose_name='Dissatisfied')),
                ('rated_3', models.PositiveIntegerField(verbose_name='Neither satisfied or dissatisfied')),
                ('rated_4', models.PositiveIntegerField(verbose_name='Satisfied')),
                ('rated_5', models.PositiveIntegerField(verbose_name='Very satisfied')),
            ],
            options={
                'ordering': ('date',),
                'get_latest_by': 'date',
            },
        ),
    ]
