# Generated by Django 2.2.24 on 2021-06-23 09:19

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_usersatisfaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('week', models.DateField(primary_key=True, serialize=False, validators=[core.models.validate_monday], verbose_name='Week commencing')),
                ('credits_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Transactions – total')),
                ('credits_by_mtp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Transactions – online')),
                ('digital_takeup', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Digital take-up')),
                ('completion_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Completion rate')),
                ('user_satisfaction', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='User satisfaction')),
                ('rated_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Very dissatisfied')),
                ('rated_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dissatisfied')),
                ('rated_3', models.PositiveIntegerField(blank=True, null=True, verbose_name='Neither satisfied or dissatisfied')),
                ('rated_4', models.PositiveIntegerField(blank=True, null=True, verbose_name='Satisfied')),
                ('rated_5', models.PositiveIntegerField(blank=True, null=True, verbose_name='Very satisfied')),
            ],
            options={
                'verbose_name': 'Performance data',
                'verbose_name_plural': 'Performance data',
                'ordering': ('week',),
                'get_latest_by': 'week',
            },
        ),
    ]
