# Generated by Django 5.2.11 on 2026-09-29 11:47

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_performancedata'),
        ('prison', '0027_add_db_comments'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='digitaltakeup',
            table_comment='Performance: number and value of credits each prison received by post and through Prisoner Money on each day, uploaded from a spreadsheet through the API admin site.',
        ),
        migrations.AlterModelTableComment(
            name='performancedata',
            table_comment="Performance: weekly figures for reporting on the service's performance, mostly built from other tables by the update_performance_data command.",
        ),
        migrations.AlterModelTableComment(
            name='usersatisfaction',
            table_comment='Performance: number of responses at each satisfaction rating each day, from the feedback export on GOV.UK publishing.',
        ),
        migrations.AlterField(
            model_name='digitaltakeup',
            name='amount_by_mtp',
            field=models.IntegerField(db_comment='Total received through Prisoner Money, in pence.', null=True, verbose_name='Amount sent digitally'),
        ),
        migrations.AlterField(
            model_name='digitaltakeup',
            name='amount_by_post',
            field=models.IntegerField(db_comment='Total received by post, in pence.', null=True, verbose_name='Amount by post'),
        ),
        migrations.AlterField(
            model_name='digitaltakeup',
            name='credits_by_mtp',
            field=models.IntegerField(db_comment='Number of credits received through Prisoner Money.', verbose_name='Credits sent digitally'),
        ),
        migrations.AlterField(
            model_name='digitaltakeup',
            name='credits_by_post',
            field=models.IntegerField(db_comment='Number of credits received by post.', verbose_name='Credits by post'),
        ),
        migrations.AlterField(
            model_name='digitaltakeup',
            name='date',
            field=models.DateField(db_comment='The day.'),
        ),
        migrations.AlterField(
            model_name='digitaltakeup',
            name='prison',
            field=models.ForeignKey(db_comment='The prison.', on_delete=django.db.models.deletion.CASCADE, to='prison.prison'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='completion_rate',
            field=models.FloatField(blank=True, db_comment='Share of people who finished sending money after starting, from 0 to 1, from web analytics.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Completion rate'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='credits_by_mtp',
            field=models.PositiveIntegerField(blank=True, db_comment='Number of credits received through Prisoner Money.', null=True, verbose_name='Transactions – online'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='credits_total',
            field=models.PositiveIntegerField(blank=True, db_comment='Number of credits received by any method.', null=True, verbose_name='Transactions – total'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='digital_takeup',
            field=models.FloatField(blank=True, db_comment='Share of credits received through Prisoner Money, from 0 to 1.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Digital take-up'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='rated_1',
            field=models.PositiveIntegerField(blank=True, db_comment='Number of responses rating the service: very dissatisfied.', null=True, verbose_name='Very dissatisfied'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='rated_2',
            field=models.PositiveIntegerField(blank=True, db_comment='Number of responses rating the service: dissatisfied.', null=True, verbose_name='Dissatisfied'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='rated_3',
            field=models.PositiveIntegerField(blank=True, db_comment='Number of responses rating the service: neither satisfied or dissatisfied.', null=True, verbose_name='Neither satisfied or dissatisfied'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='rated_4',
            field=models.PositiveIntegerField(blank=True, db_comment='Number of responses rating the service: satisfied.', null=True, verbose_name='Satisfied'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='rated_5',
            field=models.PositiveIntegerField(blank=True, db_comment='Number of responses rating the service: very satisfied.', null=True, verbose_name='Very satisfied'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='user_satisfaction',
            field=models.FloatField(blank=True, db_comment='Share of responses that were satisfied or very satisfied, from 0 to 1.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='User satisfaction'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='week',
            field=models.DateField(db_comment='The Monday the week starts on.', primary_key=True, serialize=False, validators=[core.models.validate_monday], verbose_name='Week commencing'),
        ),
        migrations.AlterField(
            model_name='usersatisfaction',
            name='date',
            field=models.DateField(db_comment='The day.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersatisfaction',
            name='rated_1',
            field=models.PositiveIntegerField(db_comment='Number of responses rating the service: very dissatisfied.', verbose_name='Very dissatisfied'),
        ),
        migrations.AlterField(
            model_name='usersatisfaction',
            name='rated_2',
            field=models.PositiveIntegerField(db_comment='Number of responses rating the service: dissatisfied.', verbose_name='Dissatisfied'),
        ),
        migrations.AlterField(
            model_name='usersatisfaction',
            name='rated_3',
            field=models.PositiveIntegerField(db_comment='Number of responses rating the service: neither satisfied or dissatisfied.', verbose_name='Neither satisfied or dissatisfied'),
        ),
        migrations.AlterField(
            model_name='usersatisfaction',
            name='rated_4',
            field=models.PositiveIntegerField(db_comment='Number of responses rating the service: satisfied.', verbose_name='Satisfied'),
        ),
        migrations.AlterField(
            model_name='usersatisfaction',
            name='rated_5',
            field=models.PositiveIntegerField(db_comment='Number of responses rating the service: very satisfied.', verbose_name='Very satisfied'),
        ),
    ]
