version: 2
updates:
  - package-ecosystem: pip
    directory: /requirements/
    ignore:
      - dependency-name: psycopg2-binary
        versions:
          - ">=2.9"
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: '-'
