CASHBOOK_OAUTH_CLIENT_ID = 'cashbook'
BANK_ADMIN_OAUTH_CLIENT_ID = 'bank-admin'
NOMS_OPS_OAUTH_CLIENT_ID = 'noms-ops'
SEND_MONEY_CLIENT_ID = 'send-money'

ALL_OAUTH_CLIENT_IDS = (
    CASHBOOK_OAUTH_CLIENT_ID,
    BANK_ADMIN_OAUTH_CLIENT_ID,
    NOMS_OPS_OAUTH_CLIENT_ID,
    SEND_MONEY_CLIENT_ID,
)
