# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-05 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20160329_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='user',
        ),
        migrations.DeleteModel(
            name='batch',
        ),
    ]
