# Generated by Django 5.2.11 on 2026-09-29 11:47

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20171109_1035'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='balance',
            table_comment='Account: closing balance of the bank account that receives prisoner money, for each day. Used by Bank Admin.',
        ),
        migrations.AlterField(
            model_name='balance',
            name='closing_balance',
            field=models.BigIntegerField(db_comment='Balance at the end of the day, in pence.'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateField(db_comment='The day.'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
