version: 2.1

executors:
  build-test-push:
    docker:
      - image: ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:deploy-tools
    environment:
      app: api
    working_directory: /tmp/repo
jobs:
  build_service_image:
    executor: build-test-push
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Build docker image
        command: . ${CIRCLE_WORKING_DIRECTORY}/.circleci/custom_scripts/build_service_image.sh
    - persist_to_workspace:
        root: imagedump
        paths:
          - '*.tar.gz'
  test:
    executor: build-test-push
    parallelism: 16
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - attach_workspace:
        at: imagedump
    - run:
        name: Test docker image
        command: . ${CIRCLE_WORKING_DIRECTORY}/.circleci/custom_scripts/test.sh
    - run:
        name: Extract test reports
        when: always
        command: |
            docker cp ${app}:/app/reports /tmp/reports
            docker rm ${app}
            docker stop postgres
            docker rm postgres
    - store_artifacts:
        path: /tmp/reports
    - store_test_results:
        path: /tmp/reports
  push_docker_image:
    executor: build-test-push
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - attach_workspace:
        at: imagedump
    - run:
        name: Push docker image
        command: . ${CIRCLE_WORKING_DIRECTORY}/.circleci/custom_scripts/push_docker_image.sh
  deploy_test:
    executor: build-test-push
    steps:
    - checkout
    - run:
        name: Deploy to test
        command: . ${CIRCLE_WORKING_DIRECTORY}/.circleci/custom_scripts/deploy_test.sh
  ecr_cleanup:
    executor: build-test-push
    steps:
    - checkout
    - run:
        name: Clean up ECR
        command: . ${CIRCLE_WORKING_DIRECTORY}/.circleci/custom_scripts/ecr_cleanup.sh
workflows:
  version: 2
  build-test-push:
    jobs:
      - build_service_image
      - test:
          requires:
            - build_service_image
      - push_docker_image:
          requires:
            - test
      - deploy_test:
          requires:
            - push_docker_image
      - ecr_cleanup:
          requires:
            - push_docker_image

