# do not run docker-compose directly, see README.md

# NB: this is only used for *local development*
# see Dockerfile for deployed version

db:
  build: conf/local-postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

django:
  build: .
  command: ./venv/bin/python run.py --requirements-file requirements/base.txt --print-task-names --verbosity 2 start --test-mode
  ports:
    - "8000:8000"
    - "8800:8800"
  links:
    - db
  environment:
    ENV: local
    DEBUG: "True"
    DJANGO_SECRET_KEY: CHANGE_ME
    DB_NAME: mtp_api
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    DB_HOST: db
    DB_PORT: 5432
