# Generated by Django 1.9.4 on 2016-06-30 14:15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0007_auto_20160517_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='prison',
            name='gender',
        ),
        migrations.AddField(
            model_name='prison',
            name='categories',
            field=models.ManyToManyField(to='prison.Category'),
        ),
        migrations.AddField(
            model_name='prison',
            name='populations',
            field=models.ManyToManyField(to='prison.Population'),
        ),
    ]
