# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0010_prison_pre_approval_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisonerlocation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
