# Generated by Django 1.10.7 on 2017-06-30 10:54
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('prison', '0014_prisonercreditnoticeemail'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='prisonerlocation',
            options={'get_latest_by': 'created', 'ordering': ('prisoner_number',)},
        ),
        migrations.AddField(
            model_name='prisonerlocation',
            name='single_offender_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prisonerlocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
