# Generated by Django 2.0.13 on 2020-10-20 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0019_auto_20200804_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrisonerBalance',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('prisoner_number', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('prison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.Prison')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='prisonerbalance',
            index_together={('prisoner_number', 'prison')},
        ),
    ]
