# Generated by Django 2.2.16 on 2020-10-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0021_prison_use_nomis_for_balances'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prisonerlocation',
            options={'get_latest_by': 'created', 'ordering': ('prisoner_number',)},
        ),
    ]
