# Generated by Django 2.2.17 on 2021-02-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0022_auto_20201007_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisonerlocation',
            name='single_offender_id',
        ),
    ]
