# Generated by Django 5.1.7 on 2025-03-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0023_removed_single_offender_id_from_prisonerlocation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prisonerbalance',
            new_name='prison_pris_prisone_e452a0_idx',
            old_fields=('prisoner_number', 'prison'),
        ),
        migrations.RenameIndex(
            model_name='prisonerlocation',
            new_name='prison_pris_prisone_6c3f58_idx',
            old_fields=('prisoner_number', 'prisoner_dob'),
        ),
    ]
