# Generated by Django 5.2.11 on 2026-09-11 12:42

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0024_rename_prisonerbalance_prisoner_number_prison_prison_pris_prisone_e452a0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrisonerValidityAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('prisoner_number_hash', models.CharField(db_index=True, max_length=64)),
                ('matched', models.BooleanField()),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
                'indexes': [models.Index(fields=['ip_address', 'created'], name='prison_pris_ip_addr_55ba4f_idx')],
            },
        ),
    ]
