# Generated by Django 5.2.11 on 2026-09-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0025_prisonervalidityattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisonervalidityattempt',
            name='prisoner_details_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
