# Generated by Django 5.2.11 on 2026-09-29 11:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0026_prisoner_details_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='category',
            table_comment='Prisons: kinds of prison, such as category A to D, young offender institution or immigration removal centre.',
        ),
        migrations.AlterModelTableComment(
            name='population',
            table_comment='Prisons: kinds of people a prison holds, such as male, female, adult or young offender.',
        ),
        migrations.AlterModelTableComment(
            name='prison',
            table_comment='Prisons: prisons and other establishments that prisoners can be sent money in.',
        ),
        migrations.AlterModelTableComment(
            name='prisonbankaccount',
            table_comment="Prisons: bank account and address of a privately run prison, which the prison's daily credits are paid into.",
        ),
        migrations.AlterModelTableComment(
            name='prisonerbalance',
            table_comment="Prisons: prisoners' account balances at prisons that do not use NOMIS for them, uploaded through the API admin site. Only balances above a set amount are uploaded, so a missing row means a low balance.",
        ),
        migrations.AlterModelTableComment(
            name='prisonercreditnoticeemail',
            table_comment='Prisons: the email address that each prison is sent its daily credit notices at, for printing and handing to prisoners.',
        ),
        migrations.AlterModelTableComment(
            name='prisonerlocation',
            table_comment='Prisons: which prison each prisoner is in, uploaded from NOMIS through NOMS Ops. Used to check the details senders give and to match credits to prisoners.',
        ),
        migrations.AlterModelTableComment(
            name='prisonervalidityattempt',
            table_comment='Prisons: each check made on Send Money that a prisoner number and date of birth match a prisoner, used to limit repeated guessing. Old records are deleted.',
        ),
        migrations.AlterModelTableComment(
            name='remittanceemail',
            table_comment="Prisons: email addresses that a privately run prison's daily credits file is sent to.",
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(db_comment='Name shown to users, such as Category B.', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_comment='Short code, such as B or IRC.', max_length=30),
        ),
        migrations.AlterField(
            model_name='population',
            name='description',
            field=models.CharField(db_comment='Name shown to users, such as Young offender.', max_length=255),
        ),
        migrations.AlterField(
            model_name='population',
            name='name',
            field=models.CharField(db_comment='Short code, such as young.', max_length=30),
        ),
        migrations.AlterField(
            model_name='prison',
            name='cms_establishment_code',
            field=models.CharField(blank=True, db_comment='Code used in the name of the daily credits file sent to a privately run prison.', max_length=10),
        ),
        migrations.AlterField(
            model_name='prison',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='prison',
            name='general_ledger_code',
            field=models.CharField(db_comment="The prison's business unit code in the finance system, used in the journals Bank Admin produces.", max_length=8),
        ),
        migrations.AlterField(
            model_name='prison',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='prison',
            name='name',
            field=models.CharField(db_comment='Full name of the prison.', max_length=500),
        ),
        migrations.AlterField(
            model_name='prison',
            name='nomis_id',
            field=models.CharField(db_comment='Code for the prison in NOMIS, such as BXI.', max_length=3, primary_key=True, serialize=False, verbose_name='NOMIS id'),
        ),
        migrations.AlterField(
            model_name='prison',
            name='pre_approval_required',
            field=models.BooleanField(db_comment='Whether security staff review credits for this prison before prison staff credit them.', default=False),
        ),
        migrations.AlterField(
            model_name='prison',
            name='private_estate',
            field=models.BooleanField(db_comment='Whether the prison is privately run. Bank Admin sends its credits to it each day.', default=False),
        ),
        migrations.AlterField(
            model_name='prison',
            name='region',
            field=models.CharField(blank=True, db_comment='Region the prison is in.', max_length=255),
        ),
        migrations.AlterField(
            model_name='prison',
            name='use_nomis_for_balances',
            field=models.BooleanField(db_comment="Whether prisoners' account balances come from NOMIS. If not, they come from prison_prisonerbalance.", default=True),
        ),
        migrations.AlterField(
            model_name='prisonbankaccount',
            name='account_number',
            field=models.CharField(db_comment='Account number of the bank account.', max_length=50),
        ),
        migrations.AlterField(
            model_name='prisonbankaccount',
            name='address_line1',
            field=models.CharField(db_comment='First line of the postal address.', max_length=250),
        ),
        migrations.AlterField(
            model_name='prisonbankaccount',
            name='address_line2',
            field=models.CharField(blank=True, db_comment='Second line of the postal address.', max_length=250),
        ),
        migrations.AlterField(
            model_name='prisonbankaccount',
            name='city',
            field=models.CharField(db_comment='Town or city.', max_length=250),
        ),
        migrations.AlterField(
            model_name='prisonbankaccount',
            name='postcode',
            field=models.CharField(db_comment='Postcode.', max_length=250),
        ),
        migrations.AlterField(
            model_name='prisonbankaccount',
            name='prison',
            field=models.OneToOneField(db_comment='The privately run prison.', on_delete=django.db.models.deletion.CASCADE, to='prison.prison'),
        ),
        migrations.AlterField(
            model_name='prisonbankaccount',
            name='sort_code',
            field=models.CharField(db_comment='Sort code of the bank account.', max_length=50),
        ),
        migrations.AlterField(
            model_name='prisonerbalance',
            name='amount',
            field=models.BigIntegerField(db_comment='Balance, in pence.'),
        ),
        migrations.AlterField(
            model_name='prisonerbalance',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='prisonerbalance',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='prisonerbalance',
            name='prison',
            field=models.ForeignKey(db_comment='Prison the prisoner is in.', on_delete=django.db.models.deletion.CASCADE, to='prison.prison'),
        ),
        migrations.AlterField(
            model_name='prisonerbalance',
            name='prisoner_number',
            field=models.CharField(db_comment='Prisoner number.', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prisonercreditnoticeemail',
            name='email',
            field=models.EmailField(db_comment='Email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='prisonercreditnoticeemail',
            name='prison',
            field=models.OneToOneField(db_comment='The prison.', on_delete=django.db.models.deletion.CASCADE, to='prison.prison'),
        ),
        migrations.AlterField(
            model_name='prisonerlocation',
            name='active',
            field=models.BooleanField(db_comment='Whether this is a current record. Records stay inactive until their whole upload has finished.', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='prisonerlocation',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='prisonerlocation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_comment='Who uploaded the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prisonerlocation',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='prisonerlocation',
            name='prison',
            field=models.ForeignKey(db_comment='Prison the prisoner is in.', on_delete=django.db.models.deletion.CASCADE, to='prison.prison'),
        ),
        migrations.AlterField(
            model_name='prisonerlocation',
            name='prisoner_dob',
            field=models.DateField(db_comment="Prisoner's date of birth, from NOMIS."),
        ),
        migrations.AlterField(
            model_name='prisonerlocation',
            name='prisoner_name',
            field=models.CharField(blank=True, db_comment="Prisoner's name, from NOMIS.", max_length=250),
        ),
        migrations.AlterField(
            model_name='prisonerlocation',
            name='prisoner_number',
            field=models.CharField(db_comment='Prisoner number, from NOMIS.', max_length=250),
        ),
        migrations.AlterField(
            model_name='prisonervalidityattempt',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='prisonervalidityattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_comment='IP address the check came from.', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='prisonervalidityattempt',
            name='matched',
            field=models.BooleanField(db_comment='Whether the details matched a prisoner.'),
        ),
        migrations.AlterField(
            model_name='prisonervalidityattempt',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='prisonervalidityattempt',
            name='prisoner_details_hash',
            field=models.CharField(blank=True, db_comment='Keyed hash of the prisoner number and date of birth together.', db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='prisonervalidityattempt',
            name='prisoner_number_hash',
            field=models.CharField(db_comment='Keyed hash of the prisoner number. The number itself is not stored.', db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='remittanceemail',
            name='email',
            field=models.EmailField(db_comment='Email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='remittanceemail',
            name='prison',
            field=models.ForeignKey(db_comment='The privately run prison.', on_delete=django.db.models.deletion.CASCADE, to='prison.prison'),
        ),
        # Django creates these many-to-many tables itself, so they cannot be given comments on the model
        migrations.RunSQL(
            sql=[
                "COMMENT ON TABLE prison_prison_populations IS 'Prisons: the kinds of people each prison holds.'",
                "COMMENT ON COLUMN prison_prison_populations.prison_id IS 'The prison.'",
                "COMMENT ON COLUMN prison_prison_populations.population_id IS 'A kind of people the prison holds.'",
                "COMMENT ON TABLE prison_prison_categories IS 'Prisons: the kinds each prison is.'",
                "COMMENT ON COLUMN prison_prison_categories.prison_id IS 'The prison.'",
                "COMMENT ON COLUMN prison_prison_categories.category_id IS 'A kind the prison is.'",
            ],
            reverse_sql=[
                'COMMENT ON TABLE prison_prison_populations IS NULL',
                'COMMENT ON COLUMN prison_prison_populations.prison_id IS NULL',
                'COMMENT ON COLUMN prison_prison_populations.population_id IS NULL',
                'COMMENT ON TABLE prison_prison_categories IS NULL',
                'COMMENT ON COLUMN prison_prison_categories.prison_id IS NULL',
                'COMMENT ON COLUMN prison_prison_categories.category_id IS NULL',
            ],
        ),
    ]
