# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 13:38
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[core.models.validate_command_name])),
                ('arg_string', models.CharField(blank=True, max_length=255)),
                ('cron_entry', models.CharField(max_length=255, validators=[core.models.validate_cron_entry])),
                ('next_execution', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
