# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scheduledcommand_delete_after_next'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='filedownload',
            unique_together=set([('label', 'date')]),
        ),
    ]
