# Generated by Django 5.2.11 on 2026-09-29 11:47

import core.models
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_framework_table_comments'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='filedownload',
            table_comment='Core: which daily files Bank Admin users have downloaded, so that missed days can be pointed out.',
        ),
        migrations.AlterModelTableComment(
            name='scheduledcommand',
            table_comment='Core: management commands that the API runs on a schedule.',
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='date',
            field=models.DateField(db_comment='The day of credits that the file covers.', db_index=True),
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='label',
            field=models.CharField(db_comment='Which kind of file was downloaded.', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='arg_string',
            field=models.CharField(blank=True, db_comment='Arguments given to the command, separated by spaces.', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='cron_entry',
            field=models.CharField(db_comment='When to run the command, as a cron schedule.', max_length=255, validators=[core.models.validate_cron_entry]),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='delete_after_next',
            field=models.BooleanField(db_comment='Whether to delete this schedule after the command next runs.', default=False),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='name',
            field=models.CharField(db_comment='Name of the management command to run.', max_length=255, validators=[core.models.validate_command_name]),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='next_execution',
            field=models.DateTimeField(blank=True, db_comment='When the command will next run.', null=True),
        ),
    ]
