# Generated by Django 1.10.6 on 2017-03-20 18:29
import logging

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def role_warning(*_):
    logging.warning('Make sure that standard Role models are created')


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('mtp_auth', '0005_applicationgroupmapping'),
    ]
    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('key_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('managed_roles', models.ManyToManyField(blank=True, related_name='_role_managed_roles_+', to='mtp_auth.Role')),
                ('other_groups', models.ManyToManyField(blank=True, related_name='_role_other_groups_+', to='auth.Group')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RunPython(role_warning, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='applicationgroupmapping',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationgroupmapping',
            name='group',
        ),
        migrations.DeleteModel(
            name='ApplicationGroupMapping',
        ),
    ]
