# Generated by Django 1.10.7 on 2017-10-31 12:56
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mtp_auth', '0007_passwordchangerequest'),
    ]
    operations = [
        migrations.AddField(
            model_name='role',
            name='login_url',
            field=models.URLField(null=True),
        ),
    ]
