# Generated by Django 2.0.13 on 2020-04-28 14:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mtp_auth', '0014_jobinformation'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='jobinformation',
            options={'verbose_name_plural': 'job information'},
        ),
    ]
