# Generated by Django 2.2.19 on 2021-03-31 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtp_auth', '0015_jobinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='prison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prison.Prison'),
        ),
    ]
