# Generated by Django 2.2.17 on 2021-03-31 15:43

from django.db import migrations


def add_UserAdmin_group_to_FIU(apps, schema_editor):
    user_model = apps.get_model('auth', 'user')
    group_model = apps.get_model('auth', 'group')
    fiu_users = user_model.objects.filter(groups__name='FIU').all()
    for fiu_user in fiu_users:
        print(f'Adding UserAdmin group from user with id {fiu_user.pk}')
        fiu_user.groups.add(group_model.objects.get(name='UserAdmin'))


def remove_UserAdmin_group_from_FIU(apps, schema_editor):
    user_model = apps.get_model('auth', 'user')
    group_model = apps.get_model('auth', 'group')
    fiu_users = user_model.objects.filter(groups__name='FIU').all()
    for fiu_user in fiu_users:
        if fiu_user.groups.filter(name='UserAdmin').exists():
            print(f'Removing UserAdmin group from user with id {fiu_user.pk}')
            fiu_user.groups.remove(group_model.objects.get(name='UserAdmin'))


class Migration(migrations.Migration):

    dependencies = [
        ('mtp_auth', '0017_add_manager_email_to_account_requests'),
    ]

    operations = [
        migrations.RunPython(code=add_UserAdmin_group_to_FIU, reverse_code=remove_UserAdmin_group_from_FIU)
    ]
