# Generated by Django 2.2.17 on 2021-03-31 15:44

from django.db import migrations

def remove_UserAdmin_group_from_security_if_not_FIU(apps, schema_editor):
    user_model = apps.get_model('auth', 'user')
    group_model = apps.get_model('auth', 'group')
    security_users = user_model.objects.filter(groups__name='Security').exclude(groups__name='FIU').all()
    for security_user in security_users:
        assert not security_user.groups.filter(name='FIU').exists()
        if security_user.groups.filter(name='UserAdmin').exists():
            print(f'Removing UserAdmin group from user with id {security_user.pk}')
            security_user.groups.remove(group_model.objects.get(name='UserAdmin'))


class Migration(migrations.Migration):

    dependencies = [
        ('mtp_auth', '0018_Add_UserAdmin_group_to_FIU'),
    ]

    operations = [
        migrations.RunPython(code=remove_UserAdmin_group_from_security_if_not_FIU)
    ]
