# Generated by Django 4.2.20 on 2025-03-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mtp_auth', '0020_flag_cashbook_uas_to_confirm_credit_notice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='other_groups',
            field=models.ManyToManyField(blank=True, related_name='+', to='auth.group'),
        ),
    ]
