# Generated by Django 5.2.11 on 2026-09-30 08:26

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mtp_auth', '0021_alter_role_other_groups'),
        ('prison', '0027_add_db_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='accountrequest',
            table_comment="User accounts: requests for a new staff account, made from the sign-in page of an app. Waiting for one of the app's user admins to accept or decline. Deleted once dealt with.",
        ),
        migrations.AlterModelTableComment(
            name='applicationusermapping',
            table_comment='User accounts: which Prisoner Money apps each user may sign in to.',
        ),
        migrations.AlterModelTableComment(
            name='failedloginattempt',
            table_comment='User accounts: sign-in attempts with a wrong password. Too many in a row lock the account for a time. Cleared after a successful sign-in.',
        ),
        migrations.AlterModelTableComment(
            name='flag',
            table_comment='User accounts: named markers that the apps set on a user, such as that a message has been seen.',
        ),
        migrations.AlterModelTableComment(
            name='jobinformation',
            table_comment='User accounts: job details that NOMS Ops users give the first time they sign in.',
        ),
        migrations.AlterModelTableComment(
            name='login',
            table_comment='User accounts: each successful sign-in by a member of staff, used for the staff sign-ins report in the API admin site. Service accounts are not recorded. Deleted after a year.',
        ),
        migrations.AlterModelTableComment(
            name='passwordchangerequest',
            table_comment='User accounts: requests to reset a forgotten password, made through a link sent by email. Deleted after 12 hours.',
        ),
        migrations.AlterModelTableComment(
            name='prisonusermapping',
            table_comment='User accounts: links a staff user to the prisons they work with (see mtp_auth_prisonusermapping_prisons).',
        ),
        migrations.AlterModelTableComment(
            name='role',
            table_comment='User accounts: the kinds of staff account, such as prison clerk or security staff, with the app and groups that each one is given.',
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='email',
            field=models.EmailField(db_comment='Email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='first_name',
            field=models.CharField(db_comment='First name.', max_length=30),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='last_name',
            field=models.CharField(db_comment='Last name.', max_length=30),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='manager_email',
            field=models.EmailField(blank=True, db_comment="Line manager's email address; required for security staff.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='prison',
            field=models.ForeignKey(blank=True, db_comment='Prison the person works at; optional for security staff.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prison.prison'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='reason',
            field=models.TextField(blank=True, db_comment='Why the person needs an account.'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='role',
            field=models.ForeignKey(db_comment='The role requested.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mtp_auth.role'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='username',
            field=models.CharField(db_comment='Requested username.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='applicationusermapping',
            name='application',
            field=models.ForeignKey(db_comment='An app the user may sign in to.', on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationusermapping',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='applicationusermapping',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='applicationusermapping',
            name='user',
            field=models.ForeignKey(db_comment='The user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='failedloginattempt',
            name='application',
            field=models.ForeignKey(db_comment='The app the attempt was made on.', on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='failedloginattempt',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='failedloginattempt',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='failedloginattempt',
            name='user',
            field=models.ForeignKey(db_comment='The user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.SlugField(db_comment='Name of the flag, such as hmpps-employee, set by the apps to remember answers and messages seen.'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='user',
            field=models.ForeignKey(db_comment='The user.', on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobinformation',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='jobinformation',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='jobinformation',
            name='prison_estate',
            field=models.CharField(db_comment='Area of the prison estate the user works in: Local prison, Regional or National.', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobinformation',
            name='tasks',
            field=models.TextField(db_comment="The user's description of their main tasks."),
        ),
        migrations.AlterField(
            model_name='jobinformation',
            name='title',
            field=models.CharField(db_comment='Job title, chosen from a list or typed in.', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobinformation',
            name='user',
            field=models.OneToOneField(db_comment='The user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='login',
            name='application',
            field=models.ForeignKey(db_comment='The app signed in to.', on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='login',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_comment='When the user signed in.'),
        ),
        migrations.AlterField(
            model_name='login',
            name='user',
            field=models.ForeignKey(db_comment='The user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordchangerequest',
            name='code',
            field=models.UUIDField(db_comment='Code in the link emailed to the user.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordchangerequest',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='passwordchangerequest',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='passwordchangerequest',
            name='user',
            field=models.ForeignKey(db_comment='The user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prisonusermapping',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='prisonusermapping',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='prisonusermapping',
            name='user',
            field=models.OneToOneField(db_comment='The user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='application',
            field=models.ForeignKey(db_comment='The app that users with this role sign in to.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='key_group',
            field=models.OneToOneField(db_comment='The group that identifies users with this role. Users are given it when their account is created.', on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='role',
            name='login_url',
            field=models.URLField(db_comment="Address of the app's sign-in page, used in emails to users."),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_comment='Name of the role, such as prison-clerk or security.', max_length=30, unique=True),
        ),
        # Django creates these many-to-many tables itself, so they cannot be given comments on the model
        migrations.RunSQL(
            sql=[
                "COMMENT ON TABLE mtp_auth_prisonusermapping_prisons IS 'User accounts: the prisons each user works with.'",
                "COMMENT ON COLUMN mtp_auth_prisonusermapping_prisons.prisonusermapping_id IS 'The user''s prison link.'",
                "COMMENT ON COLUMN mtp_auth_prisonusermapping_prisons.prison_id IS 'A prison the user works with.'",
                "COMMENT ON TABLE mtp_auth_role_other_groups IS "
                "'User accounts: the groups, besides the key group, that users with each role are given.'",
                "COMMENT ON COLUMN mtp_auth_role_other_groups.role_id IS 'The role.'",
                "COMMENT ON COLUMN mtp_auth_role_other_groups.group_id IS 'A group given with the role.'",
            ],
            reverse_sql=[
                'COMMENT ON TABLE mtp_auth_prisonusermapping_prisons IS NULL',
                'COMMENT ON COLUMN mtp_auth_prisonusermapping_prisons.prisonusermapping_id IS NULL',
                'COMMENT ON COLUMN mtp_auth_prisonusermapping_prisons.prison_id IS NULL',
                'COMMENT ON TABLE mtp_auth_role_other_groups IS NULL',
                'COMMENT ON COLUMN mtp_auth_role_other_groups.role_id IS NULL',
                'COMMENT ON COLUMN mtp_auth_role_other_groups.group_id IS NULL',
            ],
        ),
    ]
