# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0020_auto_20151203_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='prisoner_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_sort_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
