# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0021_auto_20160111_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('non-payment-credit', 'Non-payment credit')], max_length=50),
        ),
    ]
