# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0022_auto_20160111_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('taken', 'Taken')], default='taken', max_length=50),
        ),
    ]
