# Generated by Django 1.9.1 on 2016-01-28 16:20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0024_auto_20160126_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('administrative', 'Administrative'), ('online', 'Online')], default='bank_transfer', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=50),
        ),
    ]
