# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0025_auto_20160128_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='incomplete_remitter_info',
            field=models.BooleanField(default=False),
        ),
    ]
