# Generated by Django 1.9.1 on 2016-02-29 14:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0026_transaction_incomplete_sender_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='processor_type_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
