# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0028_auto_20160329_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_in_sender_field',
            field=models.BooleanField(default=False),
        ),
    ]
