# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transaction', '0030_view_dashboard_permission'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={
                'get_latest_by': 'received_at',
                'ordering': ('received_at',),
                'permissions': (
                    ('view_transaction', 'Can view transaction'),
                    ('view_dashboard', 'Can view dashboard'),
                    ('view_bank_details_transaction', 'Can view bank details of transaction'),
                    ('lock_transaction', 'Can lock transaction'),
                    ('unlock_transaction', 'Can unlock transaction'),
                    ('patch_credited_transaction', 'Can patch credited transaction'),
                    ('patch_processed_transaction', 'Can patch processed transaction')
                )
            },
        ),
    ]
