# Generated by Django 1.9.4 on 2016-04-29 16:32
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0031_latest_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('administrative', 'Administrative')], max_length=50),
        ),
    ]
