# Generated by Django 1.9.4 on 2016-05-03 10:18
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
        ('transaction', '0032_auto_20160429_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.Credit'),
        ),
    ]
