# Generated by Django 1.9.4 on 2016-05-03 10:19
from django.db import migrations


def convert_to_credits(apps, schema_editor):
    Transaction = apps.get_model('transaction', 'Transaction')
    Credit = apps.get_model('credit', 'Credit')
    for transaction in Transaction.objects.filter(category='credit', source='bank_transfer'):
        if transaction.credited:
            resolution = 'credited'
        elif transaction.refunded:
            resolution = 'refunded'
        else:
            resolution = 'pending'

        credit = Credit(
            amount=transaction.amount,
            prisoner_number=transaction.prisoner_number,
            prisoner_dob=transaction.prisoner_dob,
            prisoner_name=transaction.prisoner_name,
            prison=transaction.prison,
            reconciled=transaction.reconciled,
            received_at=transaction.received_at,
            owner=transaction.owner,
            resolution=resolution
        )
        credit.save()
        transaction.credit = credit
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0033_transaction_credit'),
    ]

    operations = [
        migrations.RunPython(convert_to_credits)
    ]
