# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0035_transaction_log_to_credit_log_conversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'received_at', 'ordering': ('received_at',), 'permissions': (('view_transaction', 'Can view transaction'), ('view_dashboard', 'Can view dashboard'), ('view_bank_details_transaction', 'Can view bank details of transaction'), ('patch_processed_transaction', 'Can patch processed transaction'))},
        ),
        migrations.AlterIndexTogether(
            name='transaction',
            index_together=set([]),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='credited',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='prison',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='prisoner_dob',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='prisoner_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='prisoner_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reconciled',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='refunded',
        ),
    ]
