# Generated by Django 1.9.4 on 2016-05-31 14:46
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0036_auto_20160505_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
