# Generated by Django 1.9.4 on 2016-06-16 11:20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0037_auto_20160531_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref_code',
            field=models.CharField(blank=True, help_text='For reconciliation', max_length=12, null=True),
        ),
    ]
