# Generated by Django 1.9.10 on 2016-10-25 11:25
from datetime import datetime, time, timedelta

from django.db import migrations
from django.utils.timezone import utc


def make_time_consistent(apps, schema_editor):
    Transaction = apps.get_model('transaction', 'Transaction')
    for transaction in Transaction.objects.all():
        eleven = time(23, 0, 0, tzinfo=utc)
        midnight = time(0, 0, 0, tzinfo=utc)
        noon = time(12, 0, 0, tzinfo=utc)

        received_at = transaction.received_at
        if received_at.timetz() in (eleven, midnight):
            # check if recorded under BST
            if received_at.timetz() == eleven:
                received_at += timedelta(days=1)

            received_at = datetime.combine(received_at.date(), noon)
            transaction.received_at = received_at
            transaction.save()

            credit = transaction.credit
            if credit:
                credit.received_at = received_at
                credit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0038_auto_20160616_1220'),
    ]

    operations = [
        migrations.RunPython(make_time_consistent)
    ]
