# Generated by Django 1.9.12 on 2016-12-14 16:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0039_consistent_received_at_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'received_at', 'ordering': ('received_at', 'id'), 'permissions': (('view_transaction', 'Can view transaction'), ('view_dashboard', 'Can view dashboard'), ('view_bank_details_transaction', 'Can view bank details of transaction'), ('patch_processed_transaction', 'Can patch processed transaction'))},
        ),
    ]
