# Generated by Django 2.2.16 on 2020-10-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0042_auto_20181016_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'received_at', 'ordering': ('received_at', 'id'), 'permissions': (('view_dashboard', 'Can view dashboard'), ('view_bank_details_transaction', 'Can view bank details of transaction'), ('patch_processed_transaction', 'Can patch processed transaction'))},
        ),
    ]
