# Generated by Django 2.2.22 on 2021-05-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0043_auto_20201007_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender_account_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_name',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_roll_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_sort_code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
