# Generated by Django 5.2.11 on 2026-09-29 10:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0042_add_db_comments'),
        ('transaction', '0043_auto_20201007_1448'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='transaction',
            table_comment='Transactions: lines from the statement of the bank account that receives prisoner money, loaded daily by the Transaction Uploader. Each bank transfer to a prisoner makes one credit.',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(db_comment='Amount in pence.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], db_comment='credit: money paid in; debit: money paid out.', db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.OneToOneField(db_comment='The credit made by this bank transfer; empty for administrative transactions.', null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.credit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='incomplete_sender_info',
            field=models.BooleanField(db_comment="Whether the sender's bank details are missing or incomplete, so the money cannot be returned to them.", default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processor_type_code',
            field=models.CharField(blank=True, db_comment='Transaction type code from the bank statement file.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received_at',
            field=models.DateTimeField(db_comment='Date on the bank statement, recorded as midday UTC.', db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_code',
            field=models.CharField(blank=True, db_comment='Reference code given during reconciliation: for bank transfers, numbered from 900001 within each day; for a card payment settlement, the code of the card payment batch.', help_text='For reconciliation', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.TextField(blank=True, db_comment='Reference given by the sender, which should be the prisoner number and date of birth.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_in_sender_field',
            field=models.BooleanField(db_comment='Whether the prisoner number and date of birth were found in the name field rather than the reference.', default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account_number',
            field=models.CharField(blank=True, db_comment="Account number of the sender's account.", max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_name',
            field=models.CharField(blank=True, db_comment="Sender's name, from the description field on the bank statement.", max_length=250),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_roll_number',
            field=models.CharField(blank=True, db_comment='Roll number, for building society accounts that use one to identify the account.', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_sort_code',
            field=models.CharField(blank=True, db_comment="Sort code of the sender's account.", max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('administrative', 'Administrative')], db_comment='bank_transfer: money sent to a prisoner by bank transfer; administrative: anything else, such as card payment settlements and returned payments.', db_index=True, max_length=50),
        ),
    ]
