# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prison', '0015_single_offender_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.PositiveIntegerField()),
                ('prisoner_number', models.CharField(blank=True, max_length=250, null=True)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('sent', 'Sent')], default='pending', max_length=50)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque')], max_length=50)),
                ('prison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prison.Prison')),
            ],
            options={
                'permissions': (('view_disbursement', 'Can view disbursements'),),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('action', models.CharField(choices=[('created', 'Created'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('sent', 'Sent')], max_length=50)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disbursement.Disbursement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('line1', models.CharField(blank=True, max_length=250, null=True)),
                ('line2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('postcode', models.CharField(blank=True, max_length=250, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'permissions': (('view_recipient', 'Can view disbursement recipients'),),
            },
        ),
        migrations.AddField(
            model_name='disbursement',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disbursement.Recipient'),
        ),
    ]
