# Generated by Django 1.10.7 on 2017-11-28 15:28
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0002_auto_20171110_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disbursement.Recipient'),
        ),
    ]
