# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0004_split_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursement',
            name='recipient',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='address_line1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='address_line2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='postcode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='recipient_first_name',
            field=models.CharField(default='Sam', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disbursement',
            name='recipient_last_name',
            field=models.CharField(default='Hall', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disbursement',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='sort_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
