# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0005_auto_20171206_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='prisoner_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
