# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0006_disbursement_prisoner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disbursement',
            options={'ordering': ('id',), 'permissions': (('view_disbursement', 'Can view disbursements'),)},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='disbursement',
            name='nomis_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('sent', 'Sent')], max_length=50),
        ),
    ]
