# Generated by Django 1.10.8 on 2018-01-18 10:21
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('disbursement', '0009_comment'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
