# Generated by Django 1.11.10 on 2018-02-20 14:40
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0013_add_indices'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['created'], name='disbursemen_created_d232ca_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['created'], name='disbursemen_created_9fa052_idx'),
        ),
    ]
