# Generated by Django 2.0.8 on 2018-08-21 13:31
# and then edited by Ian Brechin

from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Cast, Concat


def populate_invoice_number(apps, schema_editor):
    Disbursement = apps.get_model('disbursement', 'Disbursement')
    Disbursement.objects.filter(id__lt=100).update(
        invoice_number=Cast(models.F('id'), output_field=models.CharField())
    )
    Disbursement.objects.filter(id__gte=100).update(
        invoice_number=Concat(
            models.Value('PMD'),
            Cast(
                models.F('id') + settings.INVOICE_NUMBER_BASE,
                output_field=models.CharField()
            )
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0016_disbursement_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(populate_invoice_number)
    ]
