# Generated by Django 2.0.8 on 2018-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0018_auto_20181002_1429'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='disbursement',
            name='disbursemen_created_d232ca_idx',
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['created', 'id'], name='disbursemen_created_42f222_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['-created', 'id'], name='disbursemen_created_7ec31c_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['amount', 'id'], name='disbursemen_amount_8f59bd_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['-amount', 'id'], name='disbursemen_amount_6ab60e_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['prisoner_number', 'id'], name='disbursemen_prisone_fbc552_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['-prisoner_number', 'id'], name='disbursemen_prisone_11c788_idx'),
        ),
    ]
