# Generated by Django 2.0.8 on 2019-01-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0018_auto_20181002_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='resolution',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('preconfirmed', 'Pre-confirmed'), ('confirmed', 'Confirmed'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
