# Generated by Django 2.2.16 on 2020-10-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0019_auto_20181106_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disbursement',
            options={'get_latest_by': 'created', 'ordering': ('id',)},
        ),
    ]
