# Generated by Django 5.2.11 on 2026-09-30 08:18

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0020_auto_20201007_1448'),
        ('prison', '0027_add_db_comments'),
        ('security', '0036_monitoredpartialemailaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='comment',
            table_comment='Disbursements: notes that staff have added to disbursements.',
        ),
        migrations.AlterModelTableComment(
            name='disbursement',
            table_comment='Disbursements: money that a prisoner asks to send out of their prison account to a person or company, by bank transfer or cheque. Requested and confirmed by prison staff in Cashbook, then paid by the finance team from the file that Bank Admin produces.',
        ),
        migrations.AlterModelTableComment(
            name='log',
            table_comment='Disbursements: history of the actions taken on each disbursement, with who took them and when.',
        ),
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(blank=True, db_comment='What kind of note it is; reject means the reason given for cancelling the disbursement.', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(db_comment='The note.', max_length=3000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='disbursement',
            field=models.ForeignKey(db_comment='The disbursement the note is about.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='disbursement.disbursement'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='Who wrote the note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='account_number',
            field=models.CharField(blank=True, db_comment="Account number of the recipient's bank account.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='address_line1',
            field=models.CharField(blank=True, db_comment="First line of the recipient's postal address.", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='address_line2',
            field=models.CharField(blank=True, db_comment="Second line of the recipient's postal address.", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='amount',
            field=models.PositiveIntegerField(db_comment='Amount in pence.', db_index=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='city',
            field=models.CharField(blank=True, db_comment='Town or city.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='country',
            field=models.CharField(blank=True, db_comment='Country, if not the UK.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='invoice_number',
            field=models.CharField(blank=True, db_comment='Reference for the finance system, set when the disbursement is confirmed: PMD followed by a number.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque')], db_comment='How the money is paid: bank_transfer or cheque.', db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='nomis_transaction_id',
            field=models.CharField(blank=True, db_comment="ID of the transaction in NOMIS that took the money from the prisoner's account.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='postcode',
            field=models.CharField(blank=True, db_comment='Postcode.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='prison',
            field=models.ForeignKey(db_comment='Prison the prisoner was in when the request was made.', on_delete=django.db.models.deletion.PROTECT, to='prison.prison'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='prisoner_name',
            field=models.CharField(db_comment="Prisoner's name.", max_length=250),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='prisoner_number',
            field=models.CharField(db_comment='Number of the prisoner sending the money.', db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='prisoner_profile',
            field=models.ForeignKey(blank=True, db_comment='The profile of the prisoner sending the money.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements', to='security.prisonerprofile'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='recipient_email',
            field=models.EmailField(blank=True, db_comment="Recipient's email address, if given.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='recipient_first_name',
            field=models.CharField(blank=True, db_comment="Recipient's first name; empty for a company.", max_length=250),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='recipient_is_company',
            field=models.BooleanField(db_comment='Whether the recipient is a company rather than a person.', default=False),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='recipient_last_name',
            field=models.CharField(db_comment="Recipient's last name, or the company name.", max_length=250),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='recipient_profile',
            field=models.ForeignKey(blank=True, db_comment='The profile of the recipient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements', to='security.recipientprofile'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='remittance_description',
            field=models.CharField(blank=True, db_comment="Description shown on the recipient's bank statement or with the cheque.", max_length=250),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='resolution',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('preconfirmed', 'Pre-confirmed'), ('confirmed', 'Confirmed'), ('sent', 'Sent')], db_comment="pending: waiting for a second member of prison staff to confirm it; rejected: cancelled by prison staff; preconfirmed: being confirmed, while the money is taken from the prisoner's account in NOMIS; confirmed: taken from the prisoner's account; sent: included in the daily file that Bank Admin produces for the payment to be made.", db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='roll_number',
            field=models.CharField(blank=True, db_comment="Building society roll number, where the recipient's account needs one.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='sort_code',
            field=models.CharField(blank=True, db_comment="Sort code of the recipient's bank account.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('sent', 'Sent')], db_comment='What happened: created, edited, rejected, confirmed or sent.', max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='log',
            name='disbursement',
            field=models.ForeignKey(db_comment='The disbursement the action was taken on.', on_delete=django.db.models.deletion.CASCADE, to='disbursement.disbursement'),
        ),
        migrations.AlterField(
            model_name='log',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='Who took the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
