# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0024_auto_20160126_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('taken', 'Taken')], default='pending', max_length=50)),
                ('processor_id', models.CharField(max_length=250, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('recipient_name', models.CharField(blank=True, max_length=250, null=True)),
                ('prisoner_number', models.CharField(max_length=250)),
                ('prisoner_dob', models.DateField()),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
            ],
            options={
                'permissions': (('view_payment', 'Can view payment'),),
            },
        ),
    ]
