# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
        ('payment', '0004_payment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='prisoner_dob',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='prisoner_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction',
        ),
        migrations.AddField(
            model_name='payment',
            name='credit',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='credit.Credit'),
            preserve_default=False,
        ),
    ]
