# Generated by Django 1.9.4 on 2016-05-31 14:53
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20160429_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='processor_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
