# Generated by Django 1.9.4 on 2016-10-06 13:56
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0038_auto_20160616_1220'),
        ('payment', '0007_auto_20160616_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('ref_code', models.CharField(help_text='For reconciliation', max_length=12)),
                ('settlement_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.Transaction')),
            ],
            options={
                'permissions': (('view_batch', 'Can view batch'),),
                'get_latest_by': 'date',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.Batch'),
        ),
    ]
