# Generated by Django 2.0.13 on 2019-12-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('taken', 'Taken'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=50),
        ),
    ]
