# Generated by Django 2.2.16 on 2020-10-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_payment_status_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'get_latest_by': 'date', 'ordering': ('date',), 'verbose_name_plural': 'batches'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'get_latest_by': 'created', 'ordering': ('created',)},
        ),
    ]
