# Generated by Django 2.2.22 on 2021-05-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('payment', '0020_auto_20201007_1448'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='payment',
                    name='cardholder_name',
                    field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
                ),
            ],

            database_operations=[
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_cardholder_name_3a69e8e4" '
                    'ON "payment_payment" ("cardholder_name");',
                    reverse_sql='DROP INDEX "payment_payment_cardholder_name_3a69e8e4";'
                ),
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_cardholder_name_3a69e8e4_like" '
                    'ON "payment_payment" ("cardholder_name" varchar_pattern_ops);',
                    reverse_sql='DROP INDEX "payment_payment_cardholder_name_3a69e8e4_like";'
                ),
            ],
        ),
    ]
