# Generated by Django 5.2.11 on 2026-09-29 10:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0042_add_db_comments'),
        ('payment', '0020_auto_20201007_1448'),
        ('security', '0036_monitoredpartialemailaddress'),
        ('transaction', '0044_add_db_comments'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='batch',
            table_comment="Payments: one day's debit card payments, grouped during reconciliation so that they can be matched to the single amount the card payment provider pays into the bank.",
        ),
        migrations.AlterModelTableComment(
            name='billingaddress',
            table_comment='Payments: billing addresses that senders gave with debit card payments.',
        ),
        migrations.AlterModelTableComment(
            name='payment',
            table_comment='Payments: debit card payments made through Send Money and GOV.UK Pay. Each makes one credit.',
        ),
        migrations.AlterField(
            model_name='batch',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='date',
            field=models.DateField(db_comment='Day on which the card payments in this batch were received.'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ref_code',
            field=models.CharField(db_comment='Reference code given to the batch during reconciliation, counting up from 800001.', help_text='For reconciliation', max_length=12),
        ),
        migrations.AlterField(
            model_name='batch',
            name='settlement_transaction',
            field=models.OneToOneField(blank=True, db_comment='The line on the bank statement where the card payment provider paid in this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.transaction'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, db_comment='Town or city.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(blank=True, db_comment='Country.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='debit_card_sender_details',
            field=models.ForeignKey(blank=True, db_comment='The card details, in a sender profile, that this address was given with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_addresses', to='security.debitcardsenderdetails'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='line1',
            field=models.CharField(blank=True, db_comment='First line of the address.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='line2',
            field=models.CharField(blank=True, db_comment='Second line of the address.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='postcode',
            field=models.CharField(blank=True, db_comment='Postcode.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(db_comment='Amount for the prisoner, in pence.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='batch',
            field=models.ForeignKey(blank=True, db_comment="The day's batch this payment was reconciled in; empty until reconciled.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.batch'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_address',
            field=models.ForeignKey(blank=True, db_comment='Billing address given by the sender.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.billingaddress'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_brand',
            field=models.CharField(blank=True, db_comment='Card brand, such as Visa.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_expiry_date',
            field=models.CharField(blank=True, db_comment='Card expiry date, as MM/YY.', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number_first_digits',
            field=models.CharField(blank=True, db_comment='First 6 digits of the card number. The full number is never stored.', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number_last_digits',
            field=models.CharField(blank=True, db_comment='Last 4 digits of the card number.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardholder_name',
            field=models.CharField(blank=True, db_comment='Name on the card, as entered by the sender.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit',
            field=models.OneToOneField(db_comment='The credit this payment makes.', on_delete=django.db.models.deletion.CASCADE, to='credit.credit'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, db_comment="Sender's email address, used for confirmation emails.", help_text='Specified by sender for confirmation emails', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_comment='IP address the sender made the payment from.', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processor_id',
            field=models.CharField(blank=True, db_comment='ID of the payment in GOV.UK Pay.', db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipient_name',
            field=models.CharField(blank=True, db_comment="Prisoner's name as entered by the sender.", help_text='As specified by the sender', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_charge',
            field=models.PositiveIntegerField(db_comment='Charge paid by the sender on top of the amount, in pence. Zero when no charge applies.', default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('taken', 'Taken'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_comment='pending: in progress; failed: failed or in error; taken: successful; rejected: cancelled because it did not pass checks; expired: not taken in time.', db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(db_comment='Unique ID for the payment, created by Prisoner Money.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='worldpay_id',
            field=models.CharField(blank=True, db_comment='Order code from the card payment provider (Worldpay), as reported by GOV.UK Pay.', db_index=True, max_length=250, null=True),
        ),
    ]
