# Generated by Django 2.2.22 on 2021-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('payment', '0021_add_index_to_payment_on_cardholder_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='payment',
                    name='email',
                    field=models.EmailField(blank=True, db_index=True, help_text='Specified by sender for confirmation emails', max_length=254, null=True),
                ),
            ],

            database_operations=[
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_email_34088543" '
                    'ON "payment_payment" ("email");',
                    reverse_sql='DROP INDEX "payment_payment_email_34088543";',
                ),
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_email_34088543_like" '
                    'ON "payment_payment" ("email" varchar_pattern_ops);',
                    reverse_sql='DROP INDEX "payment_payment_email_34088543_like";',
                ),
            ],
        )
    ]
