# Generated by Django 2.2.22 on 2021-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('payment', '0022_add_index_to_payment_on_email'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='payment',
                    name='card_expiry_date',
                    field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
                ),
                migrations.AlterField(
                    model_name='payment',
                    name='card_number_first_digits',
                    field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
                ),
                migrations.AlterField(
                    model_name='payment',
                    name='card_number_last_digits',
                    field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
                ),
            ],

            database_operations=[
                # Indexes on 'card_expiry_date'
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_card_expiry_date_281ad0cc" '
                    'ON "payment_payment" ("card_expiry_date");',
                    reverse_sql='DROP INDEX "payment_payment_card_expiry_date_281ad0cc";',
                ),
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_card_expiry_date_281ad0cc_like" '
                    'ON "payment_payment" ("card_expiry_date" varchar_pattern_ops);',
                    reverse_sql='DROP INDEX "payment_payment_card_expiry_date_281ad0cc_like";',
                ),
                # Indexes on 'card_number_first_digits'
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_card_number_first_digits_012e4737" '
                    'ON "payment_payment" ("card_number_first_digits");',
                    reverse_sql='DROP INDEX "payment_payment_card_number_first_digits_012e4737";',
                ),
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_card_number_first_digits_012e4737_like" '
                    'ON "payment_payment" ("card_number_first_digits" varchar_pattern_ops);',
                    reverse_sql='DROP INDEX "payment_payment_card_number_first_digits_012e4737_like";',
                ),
                # Indexes on 'card_number_last_digits'
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_card_number_last_digits_e777828c" '
                    'ON "payment_payment" ("card_number_last_digits");',
                    reverse_sql='DROP INDEX "payment_payment_card_number_last_digits_e777828c";',
                ),
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_card_number_last_digits_e777828c_like" '
                    'ON "payment_payment" ("card_number_last_digits" varchar_pattern_ops);',
                    reverse_sql='DROP INDEX "payment_payment_card_number_last_digits_e777828c_like";',
                ),
            ],
        )

    ]
