# Generated by Django 2.2.22 on 2021-05-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('payment', '0024_add_index_to_billingaddress_on_postcode'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='payment',
                    name='recipient_name',
                    field=models.CharField(blank=True, db_index=True, help_text='As specified by the sender', max_length=250, null=True),
                ),
            ],

            database_operations=[
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_recipient_name_4700e276" '
                    'ON "payment_payment" ("recipient_name");',
                    reverse_sql='DROP INDEX "payment_payment_recipient_name_4700e276";'
                ),
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "payment_payment_recipient_name_4700e276_like" '
                    'ON "payment_payment" ("recipient_name" varchar_pattern_ops);',
                    reverse_sql='DROP INDEX "payment_payment_recipient_name_4700e276_like";'
                ),
            ],
        )
    ]
