# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prison', '0006_prisonerlocation_prisoner_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.PositiveIntegerField()),
                ('prisoner_number', models.CharField(blank=True, max_length=250, null=True)),
                ('prisoner_dob', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(null=True)),
                ('prisoner_name', models.CharField(blank=True, max_length=250, null=True)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('refunded', 'Refunded')], default='pending', max_length=50)),
                ('reconciled', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prison.Prison')),
            ],
            options={
                'permissions': (('view_credit', 'Can view credit'),),
            },
        ),
    ]
