# Generated by Django 1.9.4 on 2016-05-04 14:02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20160503_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='resolution',
            field=models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('credited', 'Credited'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
    ]
