# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 11:19
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.db import migrations


def fix_prisonclerk_group_permissions(apps, schema_editor):
    # make sure permissions are up to date
    apps.models_module = True
    create_permissions(apps)
    apps.models_module = None

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    try:
        clerk_group = Group.objects.get(name='PrisonClerk')
        clerk_group.permissions.clear()
        clerk_group.permissions.add(Permission.objects.get(codename='view_credit'))
        clerk_group.permissions.add(Permission.objects.get(codename='lock_credit'))
        clerk_group.permissions.add(Permission.objects.get(codename='unlock_credit'))
        clerk_group.permissions.add(Permission.objects.get(codename='patch_credited_credit'))
    except Group.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_auto_20160504_1502'),
    ]

    operations = [
        migrations.RunPython(fix_prisonclerk_group_permissions)
    ]
