# Generated by Django 1.9.4 on 2016-05-17 16:29
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_prisonclerk_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'permissions': (('view_credit', 'Can view credit'), ('view_any_credit', 'Can view any credit'), ('lock_credit', 'Can lock credit'), ('unlock_credit', 'Can unlock credit'), ('patch_credited_credit', 'Can patch credited credit'))},
        ),
    ]
