# Generated by Django 1.9.4 on 2016-06-16 11:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_auto_20160531_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'get_latest_by': 'received_at', 'ordering': ('received_at',), 'permissions': (('view_credit', 'Can view credit'), ('lock_credit', 'Can lock credit'), ('unlock_credit', 'Can unlock credit'), ('patch_credited_credit', 'Can patch credited credit'))},
        ),
    ]
