# Generated by Django 1.9.4 on 2016-11-03 12:32
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('credit', '0011_auto_20161031_1153'),
    ]
    operations = [
        migrations.CreateModel(
            name='CreditingTime',
            fields=[
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='credit.Credit')),
                ('crediting_time', models.DurationField(null=True)),
            ],
        ),
    ]
