# Generated by Django 1.9.12 on 2016-12-14 16:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0014_credit_set_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'get_latest_by': 'received_at', 'ordering': ('received_at', 'id'), 'permissions': (('view_credit', 'Can view credit'), ('view_any_credit', 'Can view any credit'), ('lock_credit', 'Can lock credit'), ('unlock_credit', 'Can unlock credit'), ('patch_credited_credit', 'Can patch credited credit'), ('review_credit', 'Can review credit'))},
        ),
    ]
