# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0017_link_to_credits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'get_latest_by': 'received_at', 'ordering': ('received_at', 'id'), 'permissions': (('view_credit', 'Can view credit'), ('view_any_credit', 'Can view any credit'), ('lock_credit', 'Can lock credit'), ('unlock_credit', 'Can unlock credit'), ('patch_credited_credit', 'Can patch credited credit'), ('review_credit', 'Can review credit'), ('credit_credit', 'Can credit credit'))},
        ),
    ]
