# Generated by Django 1.10.7 on 2017-04-13 11:15
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('credit', '0018_auto_20170314_1117'),
    ]
    operations = [
        migrations.AlterField(
            model_name='credit',
            name='prisoner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='credits', to='security.PrisonerProfile'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='sender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='credits', to='security.SenderProfile'),
        ),
    ]
