# Generated by Django 1.10.5 on 2017-05-05 15:57
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0021_auto_20170505_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingbatch',
            options={'verbose_name_plural': 'processing batches'},
        ),
    ]
