# Generated by Django 1.10.5 on 2017-05-24 10:09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0022_auto_20170505_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='nomis_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
