# Generated by Django 1.10.7 on 2017-06-30 10:54
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('credit', '0023_credit_nomis_transaction_id'),
    ]
    operations = [
        migrations.AddField(
            model_name='credit',
            name='single_offender_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
