# Generated by Django 1.10.7 on 2017-08-04 14:18
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0024_single_offender_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'get_latest_by': 'received_at', 'ordering': ('received_at', 'id'), 'permissions': (('view_credit', 'Can view credit'), ('view_any_credit', 'Can view any credit'), ('review_credit', 'Can review credit'), ('credit_credit', 'Can credit credit'))},
        ),
    ]
