# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0025_auto_20170804_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
