# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0028_add_indices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('id',)},
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['created'], name='credit_log_created_6416a6_idx'),
        ),
    ]
