# Generated by Django 2.0.8 on 2018-10-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0029_auto_20180220_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
