# Generated by Django 2.0.8 on 2018-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0030_auto_20181016_1005'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='credit',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['prisoner_number', 'prisoner_dob'], name='credit_cred_prisone_d82fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['received_at', 'id'], name='credit_cred_receive_1c4554_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['-received_at', 'id'], name='credit_cred_receive_920711_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['amount', 'id'], name='credit_cred_amount_6de366_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['-amount', 'id'], name='credit_cred_amount_7277df_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['prisoner_number', 'id'], name='credit_cred_prisone_49e443_idx'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['-prisoner_number', 'id'], name='credit_cred_prisone_ffb7bb_idx'),
        ),
    ]
