# Generated by Django 2.0.10 on 2019-02-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0031_auto_20181106_1641'),
        ('credit', '0031_private_estate'),
    ]

    operations = [
    ]
