# Generated by Django 2.0.13 on 2019-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0033_credit_resolution_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('credited', 'Credited'), ('uncredited', 'Uncredited'), ('refunded', 'Refunded'), ('reconciled', 'Reconciled'), ('reviewed', 'Reviewed'), ('manual', 'Marked for manual processing'), ('failed', 'Failed')], max_length=50),
        ),
    ]
