# Generated by Django 2.0.13 on 2020-04-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0034_payment_status_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_counted_in_sender_profile_total',
            field=models.BooleanField(default=False),
        ),
    ]
