# Generated by Django 2.0.13 on 2020-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0035_auto_20200427_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_counted_in_prisoner_profile_total',
            field=models.BooleanField(default=False),
        ),
    ]
