# Generated by Django 2.0.13 on 2020-05-13 14:45

from django.db import migrations


def populate_initial_credit_profile_total_values(apps, schema_editor):
    credit = apps.get_model('credit', 'Credit')
    # TODO CreditManager isn't bound to objects_all in the model returned
    # through this interface, find out why
    credit.objects.filter(
        sender_profile__isnull=False
    ).update(
        is_counted_in_sender_profile_total=True
    )
    credit.objects.filter(
        prisoner_profile__isnull=False
    ).update(
        is_counted_in_prisoner_profile_total=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0036_credit_is_counted_in_prisoner_profile_total'),
    ]

    operations = [
        migrations.RunPython(populate_initial_credit_profile_total_values),
    ]
