# Generated by Django 2.2.16 on 2020-10-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0038_auto_20200804_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'get_latest_by': 'received_at', 'ordering': ('received_at', 'id'), 'permissions': (('view_any_credit', 'Can view any credit'), ('review_credit', 'Can review credit'), ('credit_credit', 'Can credit credit'))},
        ),
        migrations.AlterModelOptions(
            name='privateestatebatch',
            options={'get_latest_by': 'date', 'ordering': ('date',), 'verbose_name_plural': 'private estate batches'},
        ),
        migrations.RemoveIndex(
            model_name='credit',
            name='credit_cred_owner_i_cac17f_idx',
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['owner', 'reconciled', 'resolution'], name='credit_cred_owner_i_cac17f_idx'),
        ),
    ]
