# Generated by Django 2.2.17 on 2021-02-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0039_auto_20201007_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='single_offender_id',
        ),
    ]
