# Generated by Django 2.2.22 on 2021-05-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('credit', '0040_removed_single_offender_id_from_credit'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='credit',
                    name='prisoner_name',
                    field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
                ),
            ],

            database_operations=[
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "credit_credit_prisoner_name_d077e770" '
                    'ON "credit_credit" ("prisoner_name");',
                    reverse_sql='DROP INDEX "credit_credit_prisoner_name_d077e770";',
                ),
                migrations.RunSQL(
                    'CREATE INDEX CONCURRENTLY "credit_credit_prisoner_name_d077e770_like" '
                    'ON "credit_credit" ("prisoner_name" varchar_pattern_ops);',
                    reverse_sql='DROP INDEX "credit_credit_prisoner_name_d077e770_like";',
                ),
            ],
        )
    ]
