# Generated by Django 5.2.11 on 2026-09-29 10:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0041_credit_credit_cred_created_18d594_idx'),
        ('prison', '0026_prisoner_details_hash'),
        ('security', '0036_monitoredpartialemailaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='comment',
            table_comment='Credits: notes that staff have added to credits.',
        ),
        migrations.AlterModelTableComment(
            name='credit',
            table_comment='Credits: money sent to a prisoner, by debit card (see payment_payment) or by bank transfer (see transaction_transaction). Each credit is checked, credited to the prisoner or refunded, and reconciled.',
        ),
        migrations.AlterModelTableComment(
            name='creditingtime',
            table_comment='Credits: how long each credited credit took to be credited, for performance reporting. Rebuilt in full from credit_log by the recalculate_crediting_times command.',
        ),
        migrations.AlterModelTableComment(
            name='log',
            table_comment='Credits: history of the actions taken on each credit, with who took them and when.',
        ),
        migrations.AlterModelTableComment(
            name='privateestatebatch',
            table_comment="Credits: one day's credits for a privately run prison, which are emailed to that prison by the Bank Admin app.",
        ),
        migrations.AlterModelTableComment(
            name='processingbatch',
            table_comment="Credits: credits that a member of prison staff is adding to prisoners' accounts together in Cashbook, so that nobody else processes them at the same time. Expires after 2 minutes without progress.",
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(db_comment='The note.', max_length=3000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='credit',
            field=models.ForeignKey(db_comment='The credit the note is about.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='credit.credit'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='Who wrote the note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=models.BigIntegerField(db_comment='Amount in pence.', db_index=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='blocked',
            field=models.BooleanField(db_comment="Whether the credit is held back from being credited to the prisoner, such as a bank transfer without the sender's bank details.", default=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='is_counted_in_prisoner_profile_total',
            field=models.BooleanField(db_comment="Whether this credit has been added to its prisoner profile's totals.", default=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='is_counted_in_sender_profile_total',
            field=models.BooleanField(db_comment="Whether this credit has been added to its sender profile's totals.", default=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='nomis_transaction_id',
            field=models.CharField(blank=True, db_comment="ID of the transaction in NOMIS that added the money to the prisoner's account.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='owner',
            field=models.ForeignKey(blank=True, db_comment="The member of prison staff who credited the money to the prisoner's account.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credit',
            name='prison',
            field=models.ForeignKey(blank=True, db_comment='Prison the money is for; empty if the prisoner could not be found.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prison.prison'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='prisoner_dob',
            field=models.DateField(blank=True, db_comment="Prisoner's date of birth given by the sender.", null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='prisoner_name',
            field=models.CharField(blank=True, db_comment="Prisoner's name, taken from their prisoner location when the credit is matched to them.", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='prisoner_number',
            field=models.CharField(blank=True, db_comment='Prisoner number given by the sender.', db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='prisoner_profile',
            field=models.ForeignKey(blank=True, db_comment='The profile of the prisoner receiving this credit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='security.prisonerprofile'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='private_estate_batch',
            field=models.ForeignKey(blank=True, db_comment='For a privately run prison, the daily batch this credit was sent to the prison in.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.privateestatebatch'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='received_at',
            field=models.DateTimeField(blank=True, db_comment='When the money was received: when a card payment was taken, or the date on the bank statement for a bank transfer.', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='reconciled',
            field=models.BooleanField(db_comment='Whether the credit has been included in the daily reconciliation for the bank.', default=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='resolution',
            field=models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('manual', 'Requires manual processing'), ('credited', 'Credited'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_comment="initial: card payment not yet complete; pending: waiting to be credited or refunded; manual: needs processing by hand; credited: added to the prisoner's account; refunded: returned to the sender; failed: the card payment did not complete.", db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='credit',
            name='reviewed',
            field=models.BooleanField(db_comment='Whether security staff have reviewed the credit.', default=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='sender_profile',
            field=models.ForeignKey(blank=True, db_comment='The profile of the sender of this credit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='security.senderprofile'),
        ),
        migrations.AlterField(
            model_name='creditingtime',
            name='credit',
            field=models.OneToOneField(db_comment='The credit.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='credit.credit'),
        ),
        migrations.AlterField(
            model_name='creditingtime',
            name='crediting_time',
            field=models.DurationField(db_comment='Time from receiving the money to crediting it, less any weekend days in between.', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('credited', 'Credited'), ('uncredited', 'Uncredited'), ('refunded', 'Refunded'), ('reconciled', 'Reconciled'), ('reviewed', 'Reviewed'), ('manual', 'Marked for manual processing'), ('failed', 'Failed')], db_comment='What happened: created, credited, refunded, reconciled, reviewed, manual (marked for processing by hand) or failed. locked, unlocked and uncredited are no longer used.', max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='log',
            name='credit',
            field=models.ForeignKey(db_comment='The credit the action was taken on.', on_delete=django.db.models.deletion.CASCADE, to='credit.credit'),
        ),
        migrations.AlterField(
            model_name='log',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='Who took the action; empty for automatic actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privateestatebatch',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='privateestatebatch',
            name='date',
            field=models.DateField(db_comment='Day on which the credits were received.'),
        ),
        migrations.AlterField(
            model_name='privateestatebatch',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='privateestatebatch',
            name='prison',
            field=models.ForeignKey(db_comment='The privately run prison.', on_delete=django.db.models.deletion.CASCADE, to='prison.prison'),
        ),
        migrations.AlterField(
            model_name='processingbatch',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='processingbatch',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='processingbatch',
            name='user',
            field=models.ForeignKey(db_comment='The member of prison staff crediting the batch.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # Django creates this many-to-many table itself, so it cannot be given comments on the model
        migrations.RunSQL(
            sql=[
                "COMMENT ON TABLE credit_processingbatch_credits IS 'Credits: the credits in each processing batch.'",
                "COMMENT ON COLUMN credit_processingbatch_credits.processingbatch_id IS 'The processing batch.'",
                "COMMENT ON COLUMN credit_processingbatch_credits.credit_id IS 'A credit in the batch.'",
            ],
            reverse_sql=[
                'COMMENT ON TABLE credit_processingbatch_credits IS NULL',
                'COMMENT ON COLUMN credit_processingbatch_credits.processingbatch_id IS NULL',
                'COMMENT ON COLUMN credit_processingbatch_credits.credit_id IS NULL',
            ],
        ),
    ]
