# Generated by Django 2.0.13 on 2019-09-05 20:24

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import user_event_log.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True)),
                ('kind', models.CharField(choices=[('noms_ops_search', 'Search in Intelligence Tool')], max_length=254)),
                ('api_url_path', models.CharField(db_index=True, max_length=5000, verbose_name='API URL path')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=user_event_log.models.FlexibleDjangoJSONEncoder, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp', '-pk'),
            },
        ),
    ]
