# Generated by Django 3.2.19 on 2023-06-19 13:27
from django.db import migrations, models

import user_event_log.models


class Migration(migrations.Migration):
    dependencies = [
        ('user_event_log', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='data',
            field=models.JSONField(encoder=user_event_log.models.FlexibleDjangoJSONEncoder, null=True),
        ),
    ]
