# Generated by Django 5.2.11 on 2026-09-29 11:47

import django.db.models.deletion
import user_event_log.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_event_log', '0002_alter_userevent_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='userevent',
            table_comment='User events: a lasting record of particular things users did, such as searches in NOMS Ops.',
        ),
        migrations.AlterField(
            model_name='userevent',
            name='api_url_path',
            field=models.CharField(db_comment='The API address that was requested.', db_index=True, max_length=5000, verbose_name='API URL path'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='data',
            field=models.JSONField(db_comment='Details of the event, such as the search filters used.', encoder=user_event_log.models.FlexibleDjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='kind',
            field=models.CharField(choices=[('noms_ops_search', 'Search in Intelligence Tool')], db_comment='What kind of event. Currently only noms_ops_search: a search in NOMS Ops.', max_length=254),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_comment='When it happened.', db_index=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(db_comment='Who did it.', on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
