# Generated by Django 1.10.6 on 2017-03-29 11:13
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0001_initial'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='downtime',
            options={'ordering': ('-end', '-start')},
        ),
        migrations.AddField(
            model_name='downtime',
            name='message_to_users',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
