# Generated by Django 1.10.7 on 2017-12-06 11:35
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.SmallIntegerField(choices=[(40, 'Error'), (25, 'Success'), (20, 'Info'), (30, 'Warning')]),
        ),
    ]
