# Generated by Django 5.2.11 on 2026-09-29 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_notification_areas'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='downtime',
            table_comment='Service: times when an outside service, such as GOV.UK Pay, is unavailable, so that Send Money can warn senders.',
        ),
        migrations.AlterModelTableComment(
            name='notification',
            table_comment='Service: messages shown to users of the Prisoner Money apps, such as planned maintenance.',
        ),
        migrations.AlterField(
            model_name='downtime',
            name='end',
            field=models.DateTimeField(blank=True, db_comment='When it is back; empty if not yet known.', null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='message_to_users',
            field=models.CharField(blank=True, db_comment='Message to show to users.', max_length=255),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='service',
            field=models.CharField(choices=[('gov_uk_pay', 'GOV.UK Pay')], db_comment='The outside service that is unavailable. Currently only gov_uk_pay.', max_length=50),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='start',
            field=models.DateTimeField(db_comment='When the service stops being available.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='end',
            field=models.DateTimeField(blank=True, db_comment='When to stop showing it; empty to show it until removed.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='headline',
            field=models.CharField(db_comment='Headline of the message.', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.SmallIntegerField(choices=[(20, 'Info'), (25, 'Success'), (30, 'Warning'), (40, 'Error')], db_comment='How the message is shown: 20 information, 25 success, 30 warning, 40 error.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, db_comment='Body of the message.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='public',
            field=models.BooleanField(db_comment='Whether the message can be seen before signing in.', default=False, help_text='Notifications must be public to be seen before login'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start',
            field=models.DateTimeField(db_comment='When to start showing the message.', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('bankadmin_login', 'Bank admin: before login'), ('bankadmin_dashboard', 'Bank admin: dashboard'), ('cashbook_login', 'Cashbook: before login'), ('cashbook_dashboard', 'Cashbook: dashboard'), ('cashbook_all', 'Cashbook: all apps'), ('cashbook_cashbook', 'Cashbook: cashbook app'), ('cashbook_disbursements', 'Cashbook: disbursements app'), ('noms_ops_login', 'Noms Ops: before login'), ('noms_ops_security_dashboard', 'Noms Ops: security dashboard'), ('send_money_landing', 'Send Money: landing page')], db_comment='Where the message appears, such as the Cashbook dashboard.', max_length=30),
        ),
    ]
