# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prison', '0012_prison_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferSenderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sender_name', models.CharField(blank=True, max_length=250)),
                ('sender_sort_code', models.CharField(blank=True, max_length=50)),
                ('sender_account_number', models.CharField(blank=True, max_length=50)),
                ('sender_roll_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CardholderName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DebitCardSenderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('card_number_last_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('card_expiry_date', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrisonerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('prisoner_name', models.CharField(max_length=250)),
                ('prisoner_number', models.CharField(max_length=250)),
                ('prisoner_dob', models.DateField()),
                ('credit_count', models.IntegerField(default=0)),
                ('credit_total', models.IntegerField(default=0)),
                ('prisons', models.ManyToManyField(related_name='prisoners', to='prison.Prison')),
            ],
            options={
                'permissions': (('view_prisonerprofile', 'Can view prisoner profile'),),
            },
        ),
        migrations.CreateModel(
            name='SecurityDataUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_credit_pk', models.IntegerField()),
            ],
            options={
                'ordering': ('-max_credit_pk',),
                'get_latest_by': 'max_credit_pk',
            },
        ),
        migrations.CreateModel(
            name='SenderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('credit_count', models.IntegerField(default=0)),
                ('credit_total', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('view_senderprofile', 'Can view sender profile'),),
            },
        ),
        migrations.AddField(
            model_name='prisonerprofile',
            name='senders',
            field=models.ManyToManyField(related_name='prisoners', to='security.SenderProfile'),
        ),
        migrations.AddField(
            model_name='debitcardsenderdetails',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_card_details', to='security.SenderProfile'),
        ),
        migrations.AddField(
            model_name='cardholdername',
            name='debit_card_sender_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardholder_names', related_query_name='cardholder_name', to='security.DebitCardSenderDetails'),
        ),
        migrations.AddField(
            model_name='banktransfersenderdetails',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_details', to='security.SenderProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='debitcardsenderdetails',
            unique_together=set([('card_number_last_digits', 'card_expiry_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='banktransfersenderdetails',
            unique_together=set([('sender_name', 'sender_sort_code', 'sender_account_number', 'sender_roll_number')]),
        ),
    ]
