# Generated by Django 1.9.12 on 2016-12-15 21:49
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('security', '0001_initial')]
    operations = [
        migrations.AlterModelOptions(
            name='banktransfersenderdetails',
            options={'verbose_name_plural': 'bank transfer sender details'},
        ),
        migrations.AlterModelOptions(
            name='debitcardsenderdetails',
            options={'verbose_name_plural': 'debit card sender details'},
        ),
    ]
