# Generated by Django 1.9.12 on 2017-01-12 16:07
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0012_prison_names'),
        ('security', '0003_senderemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisonerprofile',
            name='current_prison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_prisoners', to='prison.Prison'),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='prisons',
            field=models.ManyToManyField(related_name='historic_prisoners', to='prison.Prison'),
        ),
    ]
