# Generated by Django 1.9.12 on 2017-02-09 12:34
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_savedsearch_searchfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='site_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
