# Generated by Django 1.9.12 on 2017-02-20 10:37
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('security', '0007_prisonerrecipientname'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='banktransfersenderdetails',
            options={'ordering': ('created',), 'verbose_name_plural': 'bank transfer sender details'},
        ),
        migrations.AlterModelOptions(
            name='cardholdername',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='debitcardsenderdetails',
            options={'ordering': ('created',), 'verbose_name_plural': 'debit card sender details'},
        ),
        migrations.AlterModelOptions(
            name='prisonerprofile',
            options={'ordering': ('created',), 'permissions': (('view_prisonerprofile', 'Can view prisoner profile'),)},
        ),
        migrations.AlterModelOptions(
            name='prisonerrecipientname',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='senderemail',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='senderprofile',
            options={'ordering': ('created',), 'permissions': (('view_senderprofile', 'Can view sender profile'),)},
        ),
    ]
