# Generated by Django 1.10.5 on 2017-02-28 16:23
import warnings

from django.conf import settings
from django.db import migrations, models


def populate_sender_prisons(apps, _):
    if settings.ENVIRONMENT == 'prod':
        warnings.warn('Remember to run a manual update to populate sender profile prisons')
        return


class Migration(migrations.Migration):
    dependencies = [
        ('credit', '0015_auto_20161214_1603'),
        ('prison', '0013_auto_20170117_1335'),
        ('security', '0008_ordering'),
    ]
    operations = [
        migrations.AddField(
            model_name='senderprofile',
            name='prisons',
            field=models.ManyToManyField(related_name='senders', to='prison.Prison'),
        ),
        migrations.RunPython(code=populate_sender_prisons, reverse_code=migrations.RunPython.noop),
    ]
