# Generated by Django 1.10.5 on 2017-03-01 12:32
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('security', '0009_senderprofile_prisons'),
    ]
    operations = [
        migrations.AlterUniqueTogether(
            name='prisonerprofile',
            unique_together={('prisoner_number', 'prisoner_dob')},
        ),
    ]
