# Generated by Django 1.10.7 on 2017-07-13 15:04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_single_offender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcardsenderdetails',
            name='postcode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='debitcardsenderdetails',
            unique_together=set([('card_number_last_digits', 'card_expiry_date', 'postcode')]),
        ),
    ]
