# Generated by Django 2.0.8 on 2018-09-14 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


def convert_to_bank_account_records(apps, schema_editor):
    BankAccount = apps.get_model('security', 'BankAccount')
    BankTransferSenderDetails = apps.get_model('security', 'BankTransferSenderDetails')
    for sender_details in BankTransferSenderDetails.objects.all():
        bank_account, _ = BankAccount.objects.get_or_create(
            sort_code=sender_details.sender_sort_code,
            account_number=sender_details.sender_account_number,
            roll_number=sender_details.sender_roll_number,
        )
        sender_details.sender_bank_account = bank_account
        sender_details.save()


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_simple_indexes'),
    ]

    operations = [
        migrations.RenameModel(
            'PrisonerRecipientName',
            'ProvidedPrisonerName'
        ),
        migrations.AlterField(
            model_name='providedprisonername',
            name='prisoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_names', related_query_name='provided_name', to='security.PrisonerProfile'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_code', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('roll_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransferRecipientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'ordering': ('created',),
                'verbose_name_plural': 'bank transfer recipient details',
            },
        ),
        migrations.CreateModel(
            name='RecipientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('disbursement_count', models.IntegerField(default=0)),
                ('disbursement_total', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('view_recipientprofile', 'Can view recipient profile'),),
                'ordering': ('created',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='banktransfersenderdetails',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='banktransferrecipientdetails',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_details', to='security.RecipientProfile'),
        ),
        migrations.AddField(
            model_name='banktransferrecipientdetails',
            name='recipient_bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='security.BankAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('sort_code', 'account_number', 'roll_number')},
        ),
        migrations.AddField(
            model_name='banktransfersenderdetails',
            name='sender_bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='security.BankAccount'),
        ),
        migrations.RunPython(convert_to_bank_account_records),
    ]
