# Generated by Django 2.0.8 on 2018-10-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0018_auto_20181003_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisonerprofile',
            name='credit_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='credit_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='disbursement_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='disbursement_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='senderprofile',
            name='credit_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='senderprofile',
            name='credit_total',
            field=models.BigIntegerField(default=0),
        ),
    ]
