# Generated by Django 2.0.8 on 2018-10-16 11:21

from django.db import migrations


def deduplicate_prisoner_profiles(apps, schema_editor):
    PrisonerProfile = apps.get_model('security', 'PrisonerProfile')
    duplicates = []
    duplicate_numbers = set()
    for profile in PrisonerProfile.objects.all():
        all_profiles = PrisonerProfile.objects.filter(
            prisoner_number=profile.prisoner_number
        )
        if all_profiles.count() > 1:
            if profile.prisoner_number not in duplicate_numbers:
                duplicate_numbers.add(profile.prisoner_number)
                duplicates.append(all_profiles)

    for duplicate_profiles in duplicates:
        duplicate_profiles = list(duplicate_profiles.order_by('-pk'))
        prime = duplicate_profiles[0]
        for duplicate in duplicate_profiles[1:]:
            prime.credit_count += duplicate.credit_count
            prime.credit_total += duplicate.credit_total
            prime.disbursement_count += duplicate.disbursement_count
            prime.disbursement_total += duplicate.disbursement_total
            duplicate.credits.all().update(prisoner_profile=prime)
            duplicate.delete()
        prime.save()


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0019_auto_20181016_1007'),
    ]

    operations = [
        migrations.RunPython(deduplicate_prisoner_profiles),
    ]
