# Generated by Django 2.0.13 on 2019-06-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0020_auto_20181016_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisonerprofile',
            name='disbursement_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='disbursement_total',
            field=models.BigIntegerField(default=0),
        ),
    ]
