# Generated by Django 2.0.8 on 2018-10-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0021_auto_20181022_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisonertotals',
            name='prisoner_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='security.PrisonerProfile'),
        ),
        migrations.AlterField(
            model_name='sendertotals',
            name='sender_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='security.SenderProfile'),
        ),
    ]
