# Generated by Django 2.0.8 on 2018-10-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0022_auto_20181023_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipientprofile',
            name='disbursement_count',
        ),
        migrations.RemoveField(
            model_name='recipientprofile',
            name='disbursement_total',
        ),
    ]
