# Generated by Django 2.0.8 on 2018-11-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0024_auto_20181030_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisonertotals',
            name='time_period',
            field=models.CharField(choices=[('all_time', 'all time'), ('last_7_days', 'last 7 days'), ('last_30_days', 'last 30 days'), ('last_6_months', 'last 6 months')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipienttotals',
            name='time_period',
            field=models.CharField(choices=[('all_time', 'all time'), ('last_7_days', 'last 7 days'), ('last_30_days', 'last 30 days'), ('last_6_months', 'last 6 months')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sendertotals',
            name='time_period',
            field=models.CharField(choices=[('all_time', 'all time'), ('last_7_days', 'last 7 days'), ('last_30_days', 'last 30 days'), ('last_6_months', 'last 6 months')], max_length=50),
        ),
    ]
