# Generated by Django 2.0.8 on 2018-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0025_auto_20181105_1110'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipienttotals',
            index=models.Index(fields=['disbursement_count'], name='security_re_disburs_dc921c_idx'),
        ),
        migrations.AddIndex(
            model_name='recipienttotals',
            index=models.Index(fields=['disbursement_total'], name='security_re_disburs_f3e35b_idx'),
        ),
        migrations.AddIndex(
            model_name='recipienttotals',
            index=models.Index(fields=['prison_count'], name='security_re_prison__93d380_idx'),
        ),
        migrations.AddIndex(
            model_name='recipienttotals',
            index=models.Index(fields=['prisoner_count'], name='security_re_prisone_4748d4_idx'),
        ),
        migrations.AddIndex(
            model_name='recipienttotals',
            index=models.Index(fields=['time_period'], name='security_re_time_pe_00523f_idx'),
        ),
        migrations.AddIndex(
            model_name='sendertotals',
            index=models.Index(fields=['credit_count'], name='security_se_credit__763390_idx'),
        ),
        migrations.AddIndex(
            model_name='sendertotals',
            index=models.Index(fields=['credit_total'], name='security_se_credit__00ef0b_idx'),
        ),
        migrations.AddIndex(
            model_name='sendertotals',
            index=models.Index(fields=['prison_count'], name='security_se_prison__90de26_idx'),
        ),
        migrations.AddIndex(
            model_name='sendertotals',
            index=models.Index(fields=['prisoner_count'], name='security_se_prisone_b12c56_idx'),
        ),
        migrations.AddIndex(
            model_name='sendertotals',
            index=models.Index(fields=['time_period'], name='security_se_time_pe_466c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='prisonertotals',
            index=models.Index(fields=['credit_count'], name='security_pr_credit__cc7a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='prisonertotals',
            index=models.Index(fields=['credit_total'], name='security_pr_credit__d5d881_idx'),
        ),
        migrations.AddIndex(
            model_name='prisonertotals',
            index=models.Index(fields=['disbursement_count'], name='security_pr_disburs_05b153_idx'),
        ),
        migrations.AddIndex(
            model_name='prisonertotals',
            index=models.Index(fields=['disbursement_total'], name='security_pr_disburs_e91ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='prisonertotals',
            index=models.Index(fields=['sender_count'], name='security_pr_sender__85c578_idx'),
        ),
        migrations.AddIndex(
            model_name='prisonertotals',
            index=models.Index(fields=['recipient_count'], name='security_pr_recipie_edcebe_idx'),
        ),
        migrations.AddIndex(
            model_name='prisonertotals',
            index=models.Index(fields=['time_period'], name='security_pr_time_pe_2b8931_idx'),
        ),
    ]
