# Generated by Django 2.0.13 on 2019-11-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0025_check_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
