# Generated by Django 2.0.13 on 2019-03-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0027_auto_20181113_1738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prisonertotals',
            unique_together={('prisoner_profile', 'time_period')},
        ),
        migrations.AlterUniqueTogether(
            name='recipienttotals',
            unique_together={('recipient_profile', 'time_period')},
        ),
        migrations.AlterUniqueTogether(
            name='sendertotals',
            unique_together={('sender_profile', 'time_period')},
        ),
    ]
