# Generated by Django 2.0.13 on 2019-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0028_auto_20190328_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisonertotals',
            name='time_period',
            field=models.CharField(choices=[('all_time', 'all time'), ('last_7_days', 'last 7 days'), ('last_4_weeks', 'last 4 weeks'), ('last_6_months', 'last 6 months')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipienttotals',
            name='time_period',
            field=models.CharField(choices=[('all_time', 'all time'), ('last_7_days', 'last 7 days'), ('last_4_weeks', 'last 4 weeks'), ('last_6_months', 'last 6 months')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sendertotals',
            name='time_period',
            field=models.CharField(choices=[('all_time', 'all time'), ('last_7_days', 'last 7 days'), ('last_4_weeks', 'last 4 weeks'), ('last_6_months', 'last 6 months')], max_length=50),
        ),
    ]
