# Generated by Django 2.2.16 on 2020-10-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0030_migrate_check_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prisonerprofile',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='recipientprofile',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='senderprofile',
            options={'ordering': ('created',)},
        ),
    ]
