# Generated by Django 2.0.13 on 2020-11-27 13:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0030_migrate_check_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='rejection_reasons',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
