# Generated by Django 2.2.17 on 2021-02-02 17:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0032_auto_20201007_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisonerprofile',
            name='single_offender_id',
        ),
    ]
