# Generated by Django 2.2.17 on 2021-01-11 17:09

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0032_auto_20201007_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAutoAcceptRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('debit_card_sender_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_auto_accept_rules', to='security.DebitCardSenderDetails')),
                ('prisoner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_auto_accept_rules', to='security.PrisonerProfile')),
            ],
            options={
                'ordering': ('-created',),
                'unique_together': {('debit_card_sender_details', 'prisoner_profile')},
            },
        ),
        migrations.CreateModel(
            name='CheckAutoAcceptRuleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField()),
                ('reason', models.TextField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_check_auto_accept_rule_state_added_by', to=settings.AUTH_USER_MODEL)),
                ('check_auto_accept_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='security.CheckAutoAcceptRule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
