# Generated by Django 2.2.17 on 2021-01-14 12:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0033_auto_20210111_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='auto_accept_rule_state',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='checks',
                to='security.CheckAutoAcceptRuleState'
            ),
        ),
    ]
