# Generated by Django 3.2.19 on 2023-06-19 13:27
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('security', '0034_auto_20210111_1709'),
    ]
    operations = [
        migrations.AlterField(
            model_name='check',
            name='rejection_reasons',
            field=models.JSONField(default=dict),
        ),
    ]
