# Generated by Django 2.2.17 on 2021-01-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0034_auto_20210114_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='active_auto_accept_rule',
            field=models.BooleanField(default=False),
        ),
        # We add a default value within postgres itself to account for the case during the release of this functionality
        # where the database has been upgraded, but stale pods are still making requests against the database, and we want these to succeed
        # So we add a default value to the new field for back-compatibility
        migrations.RunSQL(
            sql='ALTER TABLE security_check ALTER COLUMN active_auto_accept_rule SET DEFAULT false;',
        )
    ]
