# Generated by Django 3.2.23 on 2023-11-08 17:08
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import now
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ('security', '0035_alter_check_rejection_reasons'),
    ]
    operations = [
        migrations.CreateModel(
            name='MonitoredPartialEmailAddress',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 model_utils.fields.AutoCreatedField(default=now, editable=False, verbose_name='created')),
                ('modified',
                 model_utils.fields.AutoLastModifiedField(default=now, editable=False, verbose_name='modified')),
                ('keyword',
                 models.CharField(max_length=255, unique=True,
                                  error_messages={'unique': 'Keyword already exists.'},
                                  validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'ordering': ('keyword',),
                'verbose_name': 'monitored partial email address',
                'verbose_name_plural': 'monitored partial email addresses',
            },
        ),
    ]
