# Generated by Django 5.2.11 on 2026-09-30 08:39

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0042_add_db_comments'),
        ('prison', '0027_add_db_comments'),
        ('security', '0036_monitoredpartialemailaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='bankaccount',
            table_comment='Security: bank accounts that bank transfers have come from or disbursements have been paid to.',
        ),
        migrations.AlterModelTableComment(
            name='banktransferrecipientdetails',
            table_comment='Security: the bank account of a recipient who has been paid by bank transfer.',
        ),
        migrations.AlterModelTableComment(
            name='banktransfersenderdetails',
            table_comment='Security: the name and bank account of a sender who has sent money by bank transfer.',
        ),
        migrations.AlterModelTableComment(
            name='cardholdername',
            table_comment='Security: each different cardholder name used with a debit card.',
        ),
        migrations.AlterModelTableComment(
            name='check',
            table_comment='Security: credits that security staff need to accept or reject before prison staff can credit them. At most one per credit.',
        ),
        migrations.AlterModelTableComment(
            name='checkautoacceptrule',
            table_comment='Security: pairs of debit card and prisoner whose credits security staff have agreed to accept without checking each time. Whether each is switched on is in security_checkautoacceptrulestate.',
        ),
        migrations.AlterModelTableComment(
            name='checkautoacceptrulestate',
            table_comment='Security: history of each auto-accept rule being switched on or off. The latest row is the current state.',
        ),
        migrations.AlterModelTableComment(
            name='debitcardsenderdetails',
            table_comment='Security: a debit card that money has been sent with, identified by the last 4 digits of its number, its expiry date and its billing postcode. The full card number is never stored.',
        ),
        migrations.AlterModelTableComment(
            name='monitoredpartialemailaddress',
            table_comment='Security: parts of email addresses entered by security staff in NOMS Ops.',
        ),
        migrations.AlterModelTableComment(
            name='prisonerprofile',
            table_comment='Security: one row for each prisoner who has received or sent money, grouping their credits and disbursements.',
        ),
        migrations.AlterModelTableComment(
            name='providedprisonername',
            table_comment='Security: each different name that senders have typed for a prisoner on Send Money.',
        ),
        migrations.AlterModelTableComment(
            name='recipientprofile',
            table_comment='Security: one row for each person or company that prisoners have sent money to, grouping their disbursements. Bank account details are in security_banktransferrecipientdetails.',
        ),
        migrations.AlterModelTableComment(
            name='savedsearch',
            table_comment='Security: searches and pages that NOMS Ops users have chosen to follow, with the search values in security_searchfilter.',
        ),
        migrations.AlterModelTableComment(
            name='searchfilter',
            table_comment='Security: the search values of each saved search.',
        ),
        migrations.AlterModelTableComment(
            name='senderemail',
            table_comment='Security: each different email address given by senders paying with a debit card.',
        ),
        migrations.AlterModelTableComment(
            name='senderprofile',
            table_comment='Security: one row for each person or account that has sent money, grouping their credits. Their details are in security_banktransfersenderdetails or security_debitcardsenderdetails.',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, db_comment='Account number.', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='roll_number',
            field=models.CharField(blank=True, db_comment='Building society roll number, if the account has one.', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sort_code',
            field=models.CharField(blank=True, db_comment='Sort code.', max_length=50),
        ),
        migrations.AlterField(
            model_name='banktransferrecipientdetails',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='banktransferrecipientdetails',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='banktransferrecipientdetails',
            name='recipient',
            field=models.ForeignKey(db_comment='The recipient profile these details belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_details', to='security.recipientprofile'),
        ),
        migrations.AlterField(
            model_name='banktransferrecipientdetails',
            name='recipient_bank_account',
            field=models.ForeignKey(db_comment="The recipient's bank account.", on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='security.bankaccount'),
        ),
        migrations.AlterField(
            model_name='banktransfersenderdetails',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='banktransfersenderdetails',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='banktransfersenderdetails',
            name='sender',
            field=models.ForeignKey(db_comment='The sender profile these details belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_details', to='security.senderprofile'),
        ),
        migrations.AlterField(
            model_name='banktransfersenderdetails',
            name='sender_bank_account',
            field=models.ForeignKey(db_comment="The sender's bank account.", on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='security.bankaccount'),
        ),
        migrations.AlterField(
            model_name='banktransfersenderdetails',
            name='sender_name',
            field=models.CharField(blank=True, db_comment="Sender's name from the bank statement.", max_length=250),
        ),
        migrations.AlterField(
            model_name='cardholdername',
            name='debit_card_sender_details',
            field=models.ForeignKey(db_comment='The debit card.', on_delete=django.db.models.deletion.CASCADE, related_name='cardholder_names', related_query_name='cardholder_name', to='security.debitcardsenderdetails'),
        ),
        migrations.AlterField(
            model_name='cardholdername',
            name='name',
            field=models.CharField(db_comment='Name on the card, as given in GOV.UK Pay.', max_length=250),
        ),
        migrations.AlterField(
            model_name='check',
            name='actioned_at',
            field=models.DateTimeField(blank=True, db_comment='When the check was accepted or rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='actioned_by',
            field=models.ForeignKey(blank=True, db_comment='Who accepted or rejected the check.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_check_actioned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='check',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_comment='The member of security staff dealing with the check.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_check_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='check',
            name='auto_accept_rule_state',
            field=models.ForeignKey(blank=True, db_comment='The auto-accept rule, as it stood at the time, that applied to this credit, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='security.checkautoacceptrulestate'),
        ),
        migrations.AlterField(
            model_name='check',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='check',
            name='credit',
            field=models.OneToOneField(db_comment='The credit being checked.', on_delete=django.db.models.deletion.CASCADE, related_name='security_check', to='credit.credit'),
        ),
        migrations.AlterField(
            model_name='check',
            name='decision_reason',
            field=models.TextField(blank=True, db_comment='Note given by the person who made the decision.'),
        ),
        migrations.AlterField(
            model_name='check',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, db_comment='Text shown to security staff saying why the credit needs checking.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='check',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='check',
            name='rejection_reasons',
            field=models.JSONField(db_comment='The reasons chosen when the check was rejected.', default=dict),
        ),
        migrations.AlterField(
            model_name='check',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, db_comment='Codes of the rules that led to the check.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_comment='pending: waiting for a decision; accepted: the credit may go ahead; rejected: the credit is to be refunded.', db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='checkautoacceptrule',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='checkautoacceptrule',
            name='debit_card_sender_details',
            field=models.ForeignKey(db_comment='The debit card.', on_delete=django.db.models.deletion.CASCADE, related_name='check_auto_accept_rules', to='security.debitcardsenderdetails'),
        ),
        migrations.AlterField(
            model_name='checkautoacceptrule',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='checkautoacceptrule',
            name='prisoner_profile',
            field=models.ForeignKey(db_comment='The prisoner.', on_delete=django.db.models.deletion.CASCADE, related_name='check_auto_accept_rules', to='security.prisonerprofile'),
        ),
        migrations.AlterField(
            model_name='checkautoacceptrulestate',
            name='active',
            field=models.BooleanField(db_comment='Whether the rule was switched on.'),
        ),
        migrations.AlterField(
            model_name='checkautoacceptrulestate',
            name='added_by',
            field=models.ForeignKey(blank=True, db_comment='Who switched the rule on or off.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_check_auto_accept_rule_state_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkautoacceptrulestate',
            name='auto_accept_rule',
            field=models.ForeignKey(db_comment='The auto-accept rule.', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='security.checkautoacceptrule'),
        ),
        migrations.AlterField(
            model_name='checkautoacceptrulestate',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='checkautoacceptrulestate',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='checkautoacceptrulestate',
            name='reason',
            field=models.TextField(db_comment='Reason given for the change.'),
        ),
        migrations.AlterField(
            model_name='debitcardsenderdetails',
            name='card_expiry_date',
            field=models.CharField(blank=True, db_comment='Card expiry date, as MM/YY.', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='debitcardsenderdetails',
            name='card_number_last_digits',
            field=models.CharField(blank=True, db_comment='Last 4 digits of the card number.', db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='debitcardsenderdetails',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='debitcardsenderdetails',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='debitcardsenderdetails',
            name='postcode',
            field=models.CharField(blank=True, db_comment="Postcode of the card's billing address.", db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='debitcardsenderdetails',
            name='sender',
            field=models.ForeignKey(db_comment='The sender profile these details belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='debit_card_details', to='security.senderprofile'),
        ),
        migrations.AlterField(
            model_name='monitoredpartialemailaddress',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='monitoredpartialemailaddress',
            name='keyword',
            field=models.CharField(db_comment='Part of an email address, in lower case and at least 3 characters long.', error_messages={'unique': 'Keyword already exists.'}, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='monitoredpartialemailaddress',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='credit_count',
            field=models.BigIntegerField(db_comment='Number of credits to this prisoner.', default=0),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='credit_total',
            field=models.BigIntegerField(db_comment='Total of credits to this prisoner, in pence.', default=0),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='current_prison',
            field=models.ForeignKey(db_comment='Prison the prisoner is in now, from prison_prisonerlocation; empty if they have no current location, such as after release.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_prisoners', to='prison.prison'),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='disbursement_count',
            field=models.BigIntegerField(db_comment='Number of disbursements from this prisoner.', default=0),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='disbursement_total',
            field=models.BigIntegerField(db_comment='Total of disbursements from this prisoner, in pence.', default=0),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='prisoner_dob',
            field=models.DateField(blank=True, db_comment="Prisoner's date of birth.", null=True),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='prisoner_name',
            field=models.CharField(db_comment="Prisoner's name, from NOMIS.", max_length=250),
        ),
        migrations.AlterField(
            model_name='prisonerprofile',
            name='prisoner_number',
            field=models.CharField(db_comment='Prisoner number.', db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='providedprisonername',
            name='name',
            field=models.CharField(db_comment='Name for the prisoner as typed by a sender.', max_length=250),
        ),
        migrations.AlterField(
            model_name='providedprisonername',
            name='prisoner',
            field=models.ForeignKey(db_comment='The prisoner profile.', on_delete=django.db.models.deletion.CASCADE, related_name='provided_names', related_query_name='provided_name', to='security.prisonerprofile'),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='disbursement_count',
            field=models.BigIntegerField(db_comment='Number of disbursements to this recipient.', default=0),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='disbursement_total',
            field=models.BigIntegerField(db_comment='Total of disbursements to this recipient, in pence.', default=0),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='description',
            field=models.CharField(db_comment='Name of the search shown to the user.', max_length=255),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='endpoint',
            field=models.CharField(db_comment='The API address the search is run against.', max_length=255),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='last_result_count',
            field=models.IntegerField(db_comment='Number of results when the user last looked, so that new results can be counted.', default=0),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='site_url',
            field=models.CharField(blank=True, db_comment='Address of the page in NOMS Ops that shows the search.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(db_comment='The NOMS Ops user who saved the search.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchfilter',
            name='field',
            field=models.CharField(db_comment='Name of the search field.', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchfilter',
            name='saved_search',
            field=models.ForeignKey(db_comment='The saved search.', on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='security.savedsearch'),
        ),
        migrations.AlterField(
            model_name='searchfilter',
            name='value',
            field=models.CharField(db_comment='Value searched for.', max_length=255),
        ),
        migrations.AlterField(
            model_name='senderemail',
            name='debit_card_sender_details',
            field=models.ForeignKey(db_comment='The debit card.', on_delete=django.db.models.deletion.CASCADE, related_name='sender_emails', related_query_name='sender_email', to='security.debitcardsenderdetails'),
        ),
        migrations.AlterField(
            model_name='senderemail',
            name='email',
            field=models.CharField(db_comment='Email address given by the sender on Send Money.', max_length=250),
        ),
        migrations.AlterField(
            model_name='senderprofile',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_comment='When this row was created.', default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='senderprofile',
            name='credit_count',
            field=models.BigIntegerField(db_comment='Number of credits from this sender.', default=0),
        ),
        migrations.AlterField(
            model_name='senderprofile',
            name='credit_total',
            field=models.BigIntegerField(db_comment='Total of credits from this sender, in pence.', default=0),
        ),
        migrations.AlterField(
            model_name='senderprofile',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(db_comment='When this row was last changed.', default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        # Django creates these many-to-many tables itself, so they cannot be given comments on the model
        migrations.RunSQL(
            sql=[
                "COMMENT ON TABLE security_bankaccount_monitoring_users IS 'Security: the NOMS Ops users following each bank account.'",
                "COMMENT ON COLUMN security_bankaccount_monitoring_users.bankaccount_id IS 'The bank account.'",
                "COMMENT ON COLUMN security_bankaccount_monitoring_users.user_id IS 'A user following it.'",
                "COMMENT ON TABLE security_debitcardsenderdetails_monitoring_users IS 'Security: the NOMS Ops users following each debit card.'",
                "COMMENT ON COLUMN security_debitcardsenderdetails_monitoring_users.debitcardsenderdetails_id IS 'The debit card.'",
                "COMMENT ON COLUMN security_debitcardsenderdetails_monitoring_users.user_id IS 'A user following it.'",
                "COMMENT ON TABLE security_prisonerprofile_monitoring_users IS 'Security: the NOMS Ops users following each prisoner.'",
                "COMMENT ON COLUMN security_prisonerprofile_monitoring_users.prisonerprofile_id IS 'The prisoner profile.'",
                "COMMENT ON COLUMN security_prisonerprofile_monitoring_users.user_id IS 'A user following it.'",
                "COMMENT ON TABLE security_prisonerprofile_prisons IS 'Security: the prisons each prisoner has been in when receiving or sending money.'",
                "COMMENT ON COLUMN security_prisonerprofile_prisons.prisonerprofile_id IS 'The prisoner profile.'",
                "COMMENT ON COLUMN security_prisonerprofile_prisons.prison_id IS 'A prison.'",
                "COMMENT ON TABLE security_prisonerprofile_senders IS 'Security: the senders who have sent money to each prisoner.'",
                "COMMENT ON COLUMN security_prisonerprofile_senders.prisonerprofile_id IS 'The prisoner profile.'",
                "COMMENT ON COLUMN security_prisonerprofile_senders.senderprofile_id IS 'A sender profile.'",
                "COMMENT ON TABLE security_prisonerprofile_recipients IS 'Security: the recipients each prisoner has sent money to.'",
                "COMMENT ON COLUMN security_prisonerprofile_recipients.prisonerprofile_id IS 'The prisoner profile.'",
                "COMMENT ON COLUMN security_prisonerprofile_recipients.recipientprofile_id IS 'A recipient profile.'",
                "COMMENT ON TABLE security_senderprofile_prisons IS 'Security: the prisons of the prisoners each sender has sent money to.'",
                "COMMENT ON COLUMN security_senderprofile_prisons.senderprofile_id IS 'The sender profile.'",
                "COMMENT ON COLUMN security_senderprofile_prisons.prison_id IS 'A prison.'",
                "COMMENT ON TABLE security_recipientprofile_prisons IS 'Security: the prisons of the prisoners who have sent money to each recipient.'",
                "COMMENT ON COLUMN security_recipientprofile_prisons.recipientprofile_id IS 'The recipient profile.'",
                "COMMENT ON COLUMN security_recipientprofile_prisons.prison_id IS 'A prison.'",
            ],
            reverse_sql=[
                'COMMENT ON TABLE security_bankaccount_monitoring_users IS NULL',
                'COMMENT ON COLUMN security_bankaccount_monitoring_users.bankaccount_id IS NULL',
                'COMMENT ON COLUMN security_bankaccount_monitoring_users.user_id IS NULL',
                'COMMENT ON TABLE security_debitcardsenderdetails_monitoring_users IS NULL',
                'COMMENT ON COLUMN security_debitcardsenderdetails_monitoring_users.debitcardsenderdetails_id IS NULL',
                'COMMENT ON COLUMN security_debitcardsenderdetails_monitoring_users.user_id IS NULL',
                'COMMENT ON TABLE security_prisonerprofile_monitoring_users IS NULL',
                'COMMENT ON COLUMN security_prisonerprofile_monitoring_users.prisonerprofile_id IS NULL',
                'COMMENT ON COLUMN security_prisonerprofile_monitoring_users.user_id IS NULL',
                'COMMENT ON TABLE security_prisonerprofile_prisons IS NULL',
                'COMMENT ON COLUMN security_prisonerprofile_prisons.prisonerprofile_id IS NULL',
                'COMMENT ON COLUMN security_prisonerprofile_prisons.prison_id IS NULL',
                'COMMENT ON TABLE security_prisonerprofile_senders IS NULL',
                'COMMENT ON COLUMN security_prisonerprofile_senders.prisonerprofile_id IS NULL',
                'COMMENT ON COLUMN security_prisonerprofile_senders.senderprofile_id IS NULL',
                'COMMENT ON TABLE security_prisonerprofile_recipients IS NULL',
                'COMMENT ON COLUMN security_prisonerprofile_recipients.prisonerprofile_id IS NULL',
                'COMMENT ON COLUMN security_prisonerprofile_recipients.recipientprofile_id IS NULL',
                'COMMENT ON TABLE security_senderprofile_prisons IS NULL',
                'COMMENT ON COLUMN security_senderprofile_prisons.senderprofile_id IS NULL',
                'COMMENT ON COLUMN security_senderprofile_prisons.prison_id IS NULL',
                'COMMENT ON TABLE security_recipientprofile_prisons IS NULL',
                'COMMENT ON COLUMN security_recipientprofile_prisons.recipientprofile_id IS NULL',
                'COMMENT ON COLUMN security_recipientprofile_prisons.prison_id IS NULL',
            ],
        ),
    ]
