# Generated by Django 2.0.8 on 2018-10-23 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0030_auto_20181016_1005'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disbursement', '0018_auto_20181002_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ref_number', models.IntegerField()),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('view_event', 'Can view event'),),
            },
        ),
        migrations.CreateModel(
            name='EventCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggering', models.BooleanField(default=False)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.Credit')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDisbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggering', models.BooleanField(default=False)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disbursement.Disbursement')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_subscription', 'Can view subscription'),),
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='notification.Subscription'),
        ),
        migrations.AddField(
            model_name='event',
            name='credits',
            field=models.ManyToManyField(related_name='events', through='notification.EventCredit', to='credit.Credit'),
        ),
        migrations.AddField(
            model_name='event',
            name='disbursements',
            field=models.ManyToManyField(related_name='events', through='notification.EventDisbursement', to='disbursement.Disbursement'),
        ),
        migrations.AddField(
            model_name='event',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notification.Subscription'),
        ),
    ]
