# Generated by Django 2.0.8 on 2018-10-24 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
