# Generated by Django 5.2.11 on 2026-09-29 11:47

import django.db.models.deletion
import notification.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0042_add_db_comments'),
        ('disbursement', '0020_auto_20201007_1448'),
        ('notification', '0002_auto_20201007_1448'),
        ('security', '0036_monitoredpartialemailaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='creditevent',
            table_comment='Notifications: links a notification to the credit it is about.',
        ),
        migrations.AlterModelTableComment(
            name='disbursementevent',
            table_comment='Notifications: links a notification to the disbursement it is about.',
        ),
        migrations.AlterModelTableComment(
            name='emailnotificationpreferences',
            table_comment='Notifications: users of NOMS Ops who have asked to be sent their notifications by email.',
        ),
        migrations.AlterModelTableComment(
            name='event',
            table_comment='Notifications: notifications shown to security staff in NOMS Ops about a credit or disbursement. There can be more than one for the same credit or disbursement.',
        ),
        migrations.AlterModelTableComment(
            name='prisonerprofileevent',
            table_comment='Notifications: links a notification to the prisoner profile it is about.',
        ),
        migrations.AlterModelTableComment(
            name='recipientprofileevent',
            table_comment='Notifications: links a notification to the recipient profile it is about.',
        ),
        migrations.AlterModelTableComment(
            name='senderprofileevent',
            table_comment='Notifications: links a notification to the sender profile it is about.',
        ),
        migrations.AlterField(
            model_name='creditevent',
            name='credit',
            field=models.ForeignKey(db_comment='The credit it is about.', on_delete=django.db.models.deletion.CASCADE, to='credit.credit'),
        ),
        migrations.AlterField(
            model_name='creditevent',
            name='event',
            field=models.OneToOneField(db_comment='The notification.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_event', to='notification.event'),
        ),
        migrations.AlterField(
            model_name='disbursementevent',
            name='disbursement',
            field=models.ForeignKey(db_comment='The disbursement it is about.', on_delete=django.db.models.deletion.CASCADE, to='disbursement.disbursement'),
        ),
        migrations.AlterField(
            model_name='disbursementevent',
            name='event',
            field=models.OneToOneField(db_comment='The notification.', on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_event', to='notification.event'),
        ),
        migrations.AlterField(
            model_name='emailnotificationpreferences',
            name='frequency',
            field=models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_comment='How often to send the email. Only daily is currently used.', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotificationpreferences',
            name='last_sent_at',
            field=models.DateField(blank=True, db_comment='Day the last email was sent.', null=True),
        ),
        migrations.AlterField(
            model_name='emailnotificationpreferences',
            name='user',
            field=models.OneToOneField(db_comment='The user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, db_comment='Text of the notification.', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='rule',
            field=models.CharField(db_comment='Code of the rule that created the notification.', max_length=8, validators=[notification.models.validate_rule_code]),
        ),
        migrations.AlterField(
            model_name='event',
            name='triggered_at',
            field=models.DateTimeField(blank=True, db_comment='When the credit was received or the disbursement was created.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='The user the notification is for; empty if it is for everyone who follows the rule.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prisonerprofileevent',
            name='event',
            field=models.OneToOneField(db_comment='The notification.', on_delete=django.db.models.deletion.CASCADE, related_name='prisoner_profile_event', to='notification.event'),
        ),
        migrations.AlterField(
            model_name='prisonerprofileevent',
            name='prisoner_profile',
            field=models.ForeignKey(db_comment='The prisoner profile it is about.', on_delete=django.db.models.deletion.CASCADE, to='security.prisonerprofile'),
        ),
        migrations.AlterField(
            model_name='recipientprofileevent',
            name='event',
            field=models.OneToOneField(db_comment='The notification.', on_delete=django.db.models.deletion.CASCADE, related_name='recipient_profile_event', to='notification.event'),
        ),
        migrations.AlterField(
            model_name='recipientprofileevent',
            name='recipient_profile',
            field=models.ForeignKey(db_comment='The recipient profile it is about.', on_delete=django.db.models.deletion.CASCADE, to='security.recipientprofile'),
        ),
        migrations.AlterField(
            model_name='senderprofileevent',
            name='event',
            field=models.OneToOneField(db_comment='The notification.', on_delete=django.db.models.deletion.CASCADE, related_name='sender_profile_event', to='notification.event'),
        ),
        migrations.AlterField(
            model_name='senderprofileevent',
            name='sender_profile',
            field=models.ForeignKey(db_comment='The sender profile it is about.', on_delete=django.db.models.deletion.CASCADE, to='security.senderprofile'),
        ),
    ]
