# Generated by Django 2.0.8 on 2018-10-24 14:54

from django.db import migrations, models
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_subscription_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rule',
            field=models.CharField(max_length=8, validators=[notification.models.validate_rule_code]),
        ),
    ]
