# Generated by Django 2.0.10 on 2019-02-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_emailnotificationpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ref_number',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='exclude',
        ),
    ]
