# Generated by Django 2.0.10 on 2019-02-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20190218_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
