# Generated by Django 2.0.13 on 2019-04-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0032_merge_20190218_1205'),
        ('security', '0024_migrate_saved_searches'),
        ('disbursement', '0019_auto_20181106_1641'),
        ('notification', '0008_auto_20190221_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.Credit')),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disbursement.Disbursement')),
            ],
        ),
        migrations.CreateModel(
            name='PrisonerProfileEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientProfileEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SenderProfileEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventcredit',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='eventcredit',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventdisbursement',
            name='disbursement',
        ),
        migrations.RemoveField(
            model_name='eventdisbursement',
            name='event',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='subscription',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='event',
            name='disbursements',
        ),
        migrations.RemoveField(
            model_name='event',
            name='modified',
        ),
        migrations.AddField(
            model_name='event',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventCredit',
        ),
        migrations.DeleteModel(
            name='EventDisbursement',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='senderprofileevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender_profile_event', to='notification.Event'),
        ),
        migrations.AddField(
            model_name='senderprofileevent',
            name='sender_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.SenderProfile'),
        ),
        migrations.AddField(
            model_name='recipientprofileevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_profile_event', to='notification.Event'),
        ),
        migrations.AddField(
            model_name='recipientprofileevent',
            name='recipient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.RecipientProfile'),
        ),
        migrations.AddField(
            model_name='prisonerprofileevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prisoner_profile_event', to='notification.Event'),
        ),
        migrations.AddField(
            model_name='prisonerprofileevent',
            name='prisoner_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.PrisonerProfile'),
        ),
        migrations.AddField(
            model_name='disbursementevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_event', to='notification.Event'),
        ),
        migrations.AddField(
            model_name='creditevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_event', to='notification.Event'),
        ),
    ]
